"""Task-scoped Atlas context packs.

AGENTS.md generation is one repository-memory output. This module is another:
given a repository and a natural-language task, select compact, evidence-backed
context for an AI coding agent without dumping whole files.
"""

from __future__ import annotations

import os
import re
from collections import Counter
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

from . import repository_memory as _repo_memory
from .evidence_engine.evidence_builder import EvidenceStore
from .evidence_engine.symbol_evidence import file_symbol_evidence

_CHARS_PER_TOKEN = 4.0
_DEFAULT_MAX_FILES = 16
_MAX_EXCLUDED = 12
_MAX_SNIPPET_LINES = 6

_ACTION_WORDS = {
    "fix": {"fix", "bug", "regression", "broken", "debug", "error", "failure", "crash", "failing"},
    "refactor": {"refactor", "clean", "rework", "rename", "move", "simplify"},
    "add": {"add", "implement", "support", "feature", "new", "extend"},
    "remove": {"remove", "delete", "drop", "deprecate"},
    "test": {"test", "tests", "coverage", "pytest", "unit", "integration"},
    "rename": {"rename"},
    "debug": {"debug", "trace", "investigate", "diagnose"},
}

_STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "can", "for", "from",
    "how", "in", "into", "is", "it", "its", "of", "on", "or", "our", "that",
    "the", "this", "to", "with", "when", "where", "why", "should", "would",
    "could", "make", "need", "needs", "update", "change", "changes", "code",
    "file", "files", "module", "modules", "repo", "repository",
}

_CODE_EXTS = {
    ".py", ".pyi", ".js", ".jsx", ".ts", ".tsx", ".go", ".rs", ".java", ".kt",
    ".rb", ".php", ".cs", ".c", ".cc", ".cpp", ".h", ".hpp", ".mjs", ".cjs",
}

_DOC_EXTS = {".md", ".rst", ".txt", ".adoc"}
_CONFIG_NAMES = {
    "pyproject.toml", "setup.py", "setup.cfg", "package.json", "Makefile",
    "tox.ini", "pytest.ini", "mypy.ini", "ruff.toml", ".eslintrc.json",
}

_NOISE_PARTS = {
    ".git", ".hg", ".svn", ".venv", "venv", "env", "node_modules", "vendor",
    "dist", "build", ".next", "__pycache__", ".tox", ".mypy_cache",
}

_GENERATED_HINTS = {
    "generated", "autogenerated", "vendor", "vendored", "bundle", "min.js",
    ".lock", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
}

_ALL_ACTION_WORDS = set().union(*_ACTION_WORDS.values())
_SHORT_TECH_TERMS = {"api", "orm", "jwt", "ssl", "cli", "sql", "css", "dom"}
_PATH_ONLY_TERMS = {"test", "tests", "fix", "add", "new", "bug", "debug", "refactor"}
_COMPONENT_CAPS = {
    "direct": 100.0,
    "symbol": 70.0,
    "content": 65.0,
    "path": 60.0,
    "exact": 80.0,
    "dependency": 38.0,
    "subsystem": 35.0,
    "package": 45.0,
    "canonical": 74.0,
    "compound": 54.0,
    "framework": 92.0,
    "test": 42.0,
    "importance": 18.0,
    "risk": 18.0,
}

_TERM_ALIASES = {
    "queryset": {"query", "queries"},
    "querysets": {"query", "queries"},
    "filtering": {"filter", "filters"},
    "filtered": {"filter", "filters"},
    "template_tag": {"templatetag", "templatetags", "defaulttags", "library"},
    "template-tag": {"templatetag", "templatetags", "defaulttags", "library"},
}


@dataclass
class TaskSignals:
    raw: str
    actions: List[str] = field(default_factory=list)
    files: List[str] = field(default_factory=list)
    modules: List[str] = field(default_factory=list)
    concepts: List[str] = field(default_factory=list)
    domain_keywords: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "raw": self.raw,
            "actions": list(self.actions),
            "files": list(self.files),
            "modules": list(self.modules),
            "concepts": list(self.concepts),
            "domain_keywords": list(self.domain_keywords),
        }


@dataclass
class Candidate:
    path: str
    score: float = 0.0
    reasons: List[str] = field(default_factory=list)
    components: Dict[str, float] = field(default_factory=dict)
    excluded_reason: str = ""

    def add(self, amount: float, reason: str, component: str) -> None:
        if amount <= 0:
            return
        cap = _COMPONENT_CAPS.get(component)
        current = self.components.get(component, 0.0)
        applied = amount
        if cap is not None:
            applied = max(0.0, min(amount, cap - current))
        if applied <= 0:
            return
        self.score += applied
        self.components[component] = round(current + applied, 2)
        if reason and reason not in self.reasons:
            self.reasons.append(reason)


def estimate_tokens(text: str) -> int:
    return max(0, round(len(text or "") / _CHARS_PER_TOKEN))


def _norm_path(path: str) -> str:
    return (path or "").replace("\\", "/").strip().lstrip("./")


def _path_parts(path: str) -> List[str]:
    bits = re.split(r"[^A-Za-z0-9_]+", _norm_path(path).lower())
    out: List[str] = []
    for bit in bits:
        if not bit:
            continue
        out.append(bit)
        if len(bit) > 4 and bit.endswith("s"):
            out.append(bit[:-1])
        out.extend(x for x in bit.split("_") if len(x) > 2)
        out.extend(x[:-1] for x in bit.split("_") if len(x) > 4 and x.endswith("s"))
    return list(dict.fromkeys(out))


def _term_variants(term: str) -> Set[str]:
    base = (term or "").lower().strip("_-")
    if not base:
        return set()
    seeds = {base, base.replace("_", "-"), base.replace("-", "_")}
    out: Set[str] = set()
    for seed in seeds:
        if not seed:
            continue
        out.add(seed)
        out.update(_TERM_ALIASES.get(seed, set()))
        if seed.endswith("ies") and len(seed) > 4:
            out.add(seed[:-3] + "y")
        if seed.endswith("y") and len(seed) > 3:
            out.add(seed[:-1] + "ies")
        if seed.endswith("s") and len(seed) > 4:
            out.add(seed[:-1])
        elif len(seed) > 3:
            out.add(seed + "s")
    return out


def _expanded_path_parts(path: str) -> Set[str]:
    expanded: Set[str] = set()
    for part in _path_parts(path):
        expanded.update(_term_variants(part))
    return expanded


def _term_matches_text(term: str, *, parts: Set[str], text: str) -> bool:
    text_l = text.lower()
    for variant in _term_variants(term):
        if variant in parts or variant in text_l:
            return True
    return False


def _stem_related_terms(stem: str, terms: Iterable[str]) -> List[str]:
    """Terms morphologically related to a file stem by containment.

    Catches synonym/compound retrieval that exact-token matching misses, e.g.
    stem ``query`` <-> task term ``queryset``, or term ``tags`` inside stem
    ``defaulttags``. Bounded to >=4 chars on both sides to avoid noise.
    """
    s = (stem or "").lower()
    if len(s) < 4:
        return []
    out: List[str] = []
    for term in terms:
        for variant in _term_variants(term):
            if len(variant) < 4:
                continue
            if variant in s or s in variant:
                out.append(term)
                break
    return out


def _stem(path: str) -> str:
    return os.path.splitext(os.path.basename(_norm_path(path)))[0].lower()


def _path_depth(path: str) -> int:
    return len([p for p in _norm_path(path).split("/") if p])


def _parent_dir(path: str) -> str:
    bits = [p for p in _norm_path(path).split("/") if p]
    if len(bits) < 2:
        return ""
    return bits[-2].lower()


def _canonical_package_root_hits(path: str, terms: Iterable[str]) -> List[str]:
    if os.path.basename(_norm_path(path)).lower() != "__init__.py":
        return []
    parent_parts = _expanded_path_parts(_parent_dir(path))
    return [term for term in terms if _term_matches_text(term, parts=parent_parts, text=_parent_dir(path))]


def _compound_filename_hits(path: str, terms: Iterable[str]) -> List[str]:
    stem = _stem(path)
    if stem in {"__init__", "base", "utils", "helpers"}:
        return []
    stem_parts = _expanded_path_parts(stem)
    hits = [term for term in terms if _term_matches_text(term, parts=stem_parts, text=stem)]
    return hits if len(hits) >= 2 else []


def _framework_concept_boost(path: str, signals: TaskSignals) -> Tuple[int, str]:
    p = _norm_path(path).lower()
    stem = _stem(path)
    concepts = set(signals.concepts) | set(signals.domain_keywords)
    has_queryset = bool(concepts & {"queryset", "querysets"})
    has_filtering = bool(concepts & {"filtering", "filtered", "filter", "filters"})
    has_related = "related" in concepts
    if has_queryset and has_filtering and "django/db/models" in p and stem == "query":
        return 92, "framework query engine for queryset filtering"
    if has_queryset and has_related and "django/db/models" in p and stem == "query":
        return 78, "framework query engine for related queryset changes"
    has_template = "template" in concepts or "templates" in concepts
    has_tag = bool(concepts & {"tag", "tags", "template_tag", "template-tag"})
    if has_template and has_tag and p.startswith("django/template/") and stem in {"defaulttags", "library"}:
        return 92, "framework extension point for template tags"
    return 0, ""


def _tokenize(text: str) -> List[str]:
    raw = re.findall(r"[A-Za-z][A-Za-z0-9_]{1,}", text or "")
    out: List[str] = []
    for tok in raw:
        pieces = [tok]
        # Split common CamelCase names without requiring a dependency.
        camel = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", tok)
        if camel != tok:
            pieces.extend(camel.split())
        for piece in pieces:
            low = piece.lower().strip("_")
            if len(low) < 3 or low in _STOPWORDS:
                continue
            out.append(low)
    return list(dict.fromkeys(out))


def _ngrams(tokens: List[str]) -> List[str]:
    grams: List[str] = []
    for i in range(len(tokens) - 1):
        if len(tokens[i]) > 2 and len(tokens[i + 1]) > 2:
            grams.append(f"{tokens[i]}_{tokens[i + 1]}")
            grams.append(f"{tokens[i]}-{tokens[i + 1]}")
    return grams


def parse_task(task: str) -> TaskSignals:
    text = task or ""
    lower = text.lower()
    actions: List[str] = []
    for action, words in _ACTION_WORDS.items():
        if any(re.search(rf"\b{re.escape(w)}\b", lower) for w in words):
            actions.append(action)

    files: List[str] = []
    for match in re.findall(r"(?<![\w.-])([A-Za-z0-9_.\-/\\]+(?:\.[A-Za-z0-9_]+))(?![\w.-])", text):
        norm = _norm_path(match)
        ext = os.path.splitext(norm)[1].lower()
        if "/" in norm or ext in _CODE_EXTS or ext in _DOC_EXTS or os.path.basename(norm) in _CONFIG_NAMES:
            files.append(norm)

    modules: List[str] = []
    for match in re.findall(r"\b([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*){1,})\b", text):
        if "." in match and not match.lower().endswith(tuple(_CODE_EXTS)):
            modules.append(match)

    concepts = _tokenize(text)
    concepts.extend(_ngrams(concepts))
    # File names and dotted module tails are useful retrieval terms too.
    for file_path in files:
        concepts.extend(_path_parts(file_path))
    for module in modules:
        concepts.extend(_tokenize(module.replace(".", " ")))

    domain_keywords = [
        t for t in concepts
        if t not in set(actions) and len(t) >= 4 and t not in _STOPWORDS
    ][:24]

    return TaskSignals(
        raw=text.strip(),
        actions=list(dict.fromkeys(actions)),
        files=list(dict.fromkeys(files)),
        modules=list(dict.fromkeys(modules)),
        concepts=list(dict.fromkeys(concepts))[:40],
        domain_keywords=list(dict.fromkeys(domain_keywords))[:24],
    )


def _is_test_path(path: str) -> bool:
    p = _norm_path(path).lower()
    base = os.path.basename(p)
    return (
        "/test" in p
        or p.startswith("test")
        or base.startswith("test_")
        or base.endswith("_test.py")
        or ".test." in base
        or ".spec." in base
    )


def _is_code_like_path(path: str) -> bool:
    p = _norm_path(path)
    ext = os.path.splitext(p)[1].lower()
    return ext in _CODE_EXTS or os.path.basename(p) in _CONFIG_NAMES


def _is_test_file_candidate(path: str) -> bool:
    return _is_test_path(path) and _is_code_like_path(path)


def _is_doc_path(path: str) -> bool:
    p = _norm_path(path).lower()
    ext = os.path.splitext(p)[1]
    return ext in _DOC_EXTS or p.startswith("docs/") or "/docs/" in p


def _is_config_path(path: str) -> bool:
    return os.path.basename(_norm_path(path)) in _CONFIG_NAMES


def _noise_reason(path: str) -> str:
    p = _norm_path(path).lower()
    parts = set(p.split("/"))
    if parts & _NOISE_PARTS:
        return "vendor/build/cache path"
    if p.startswith(".github/") or "/.github/" in p:
        return "CI helper path"
    if any(h in p for h in _GENERATED_HINTS):
        return "generated/lock artifact"
    if _is_test_path(p) and not _is_code_like_path(p):
        return "non-code test fixture"
    if "/migrations/" in p and not any(x in p for x in ("model", "schema")):
        return "migration file, not primary implementation"
    return ""


def _file_role(path: str, file_meta: Dict[str, Any]) -> str:
    role = str(file_meta.get("role") or "")
    if role:
        return role
    if _is_test_path(path):
        return "test_code"
    if _is_doc_path(path):
        return "documentation"
    if _is_config_path(path):
        return "configuration"
    return "production_code"


def _safe_rel(repo_path: str, path: str) -> str:
    rel = _norm_path(path)
    if os.path.isabs(path):
        try:
            rel = os.path.relpath(path, repo_path).replace("\\", "/")
        except ValueError:
            rel = _norm_path(path)
    return rel


def _resolve_file_mention(mention: str, all_paths: Set[str]) -> List[str]:
    m = _norm_path(mention)
    low = m.lower()
    matches: List[str] = []
    by_low = {p.lower(): p for p in all_paths}
    if low in by_low:
        return [by_low[low]]
    for p in all_paths:
        pl = p.lower()
        if pl.endswith("/" + low) or os.path.basename(pl) == os.path.basename(low):
            matches.append(p)
    return sorted(matches)[:8]


def _module_to_path_candidates(module: str) -> List[str]:
    parts = module.replace(".", "/")
    return [parts + ".py", parts + "/__init__.py", "src/" + parts + ".py", "src/" + parts + "/__init__.py"]


def _graph_adjacency(graph: Dict[str, Any]) -> Tuple[Dict[str, Set[str]], Dict[str, Set[str]], Dict[str, int], Dict[str, int]]:
    id_to_path: Dict[str, str] = {}
    for node in graph.get("nodes") or []:
        if node.get("type") == "module" and node.get("path"):
            id_to_path[str(node.get("id"))] = _norm_path(str(node.get("path")))
    imports: Dict[str, Set[str]] = {}
    imported_by: Dict[str, Set[str]] = {}
    fan_in: Dict[str, int] = {}
    fan_out: Dict[str, int] = {}
    for edge in graph.get("edges") or []:
        if edge.get("type") != "imports" or not edge.get("resolved"):
            continue
        src = id_to_path.get(str(edge.get("from")))
        dst = id_to_path.get(str(edge.get("to")))
        if not src or not dst:
            continue
        imports.setdefault(src, set()).add(dst)
        imported_by.setdefault(dst, set()).add(src)
        fan_in[dst] = fan_in.get(dst, 0) + 1
        fan_out[src] = fan_out.get(src, 0) + 1
    return imports, imported_by, fan_in, fan_out


def _subsystem_for_path(path: str, memory: Dict[str, Any], index: Dict[str, Any]) -> str:
    p = _norm_path(path)
    c = memory.get("agent_context") or {}
    for pkg in c.get("packages") or []:
        prefix = _norm_path(str(pkg.get("path") or ""))
        if prefix and (p == prefix or p.startswith(prefix + "/")):
            return prefix
    for sub in c.get("key_subsystems") or []:
        prefix = _norm_path(str(sub.get("name") or ""))
        if prefix and prefix not in {"tests", "documentation", "configuration"}:
            if p == prefix or p.startswith(prefix + "/"):
                return prefix
    for sub in index.get("subsystems") or []:
        prefix = _norm_path(str(sub.get("name") or ""))
        if prefix and (p == prefix or p.startswith(prefix + "/")):
            return prefix
    first = p.split("/", 1)[0]
    return first or "(root)"


def _candidate(candidates: Dict[str, Candidate], path: str) -> Candidate:
    norm = _norm_path(path)
    cand = candidates.get(norm)
    if cand is None:
        cand = Candidate(path=norm)
        candidates[norm] = cand
    return cand


def _load_store(raw: Dict[str, Any]) -> Optional[EvidenceStore]:
    if not raw:
        return None
    try:
        return EvidenceStore.from_dict(raw)
    except Exception:
        return None


def _read_small_file(repo_path: str, rel: str, max_chars: int = 200_000) -> str:
    path = os.path.join(repo_path, rel.replace("/", os.sep))
    try:
        if os.path.getsize(path) > max_chars:
            return ""
        with open(path, "r", encoding="utf-8", errors="ignore") as fh:
            return fh.read()
    except OSError:
        return ""


def _retrieval_terms(signals: TaskSignals) -> List[str]:
    terms: List[str] = []
    for term in list(signals.domain_keywords) + list(signals.concepts):
        t = term.lower().strip("_-")
        if not t or t in _STOPWORDS or t in _PATH_ONLY_TERMS or t in _ALL_ACTION_WORDS:
            continue
        # Keep short domain nouns (e.g. "tag") when an inflected variant is a
        # real, indexable token ("tags") so synonym/plural retrieval can fire.
        if len(t) < 4 and t not in _SHORT_TECH_TERMS and not any(len(v) >= 4 for v in _term_variants(t)):
            continue
        terms.append(t)
    return list(dict.fromkeys(terms))[:32]


def _content_terms(signals: TaskSignals) -> List[str]:
    out: List[str] = []
    for term in _retrieval_terms(signals):
        if len(term) >= 5 or "_" in term or "-" in term or term in _SHORT_TECH_TERMS:
            out.append(term)
    # Keep dotted/file terms literal when present.
    for file_path in signals.files:
        out.extend(t for t in _path_parts(file_path) if len(t) >= 4)
    return list(dict.fromkeys(out))[:12]


def _snippet(repo_path: str, rel: str, terms: Iterable[str]) -> str:
    text = _read_small_file(repo_path, rel, max_chars=120_000)
    if not text:
        return ""
    lines = text.splitlines()
    lows = [t.lower() for t in terms if len(t) > 2]
    hit = 0
    for idx, line in enumerate(lines):
        ll = line.lower()
        if any(t in ll for t in lows):
            hit = idx
            break
    start = max(0, hit - 2)
    end = min(len(lines), start + _MAX_SNIPPET_LINES)
    return "\n".join(f"{i + 1}: {lines[i][:160]}" for i in range(start, end))


def _package_for_path(path: str, memory: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    p = _norm_path(path)
    c = memory.get("agent_context") or {}
    matches = []
    for pkg in c.get("packages") or []:
        prefix = _norm_path(str(pkg.get("path") or ""))
        if prefix and (p == prefix or p.startswith(prefix + "/")):
            matches.append((len(prefix), pkg))
    if not matches:
        return None
    return sorted(matches, key=lambda item: -item[0])[0][1]


def _usable_memory(memory: Optional[Dict[str, Any]], repo_path: str) -> bool:
    if not memory:
        return False
    if os.path.abspath(str(memory.get("repo_path") or "")) != os.path.abspath(repo_path):
        return False
    c = memory.get("agent_context") or {}
    return bool(c.get("commands") or c.get("key_subsystems") or c.get("critical_files"))


def _commands_for_pack(selected: List[Dict[str, Any]], signals: TaskSignals, memory: Dict[str, Any]) -> List[str]:
    c = memory.get("agent_context") or {}
    commands: List[str] = []
    action_needs = set(signals.actions)
    wanted = ["test", "lint", "build"] if action_needs & {"fix", "refactor", "add", "test", "debug"} else ["test"]
    seen: Set[str] = set()

    for item in selected:
        pkg = _package_for_path(item["path"], memory)
        if not pkg:
            continue
        pkg_cmds = pkg.get("commands") or {}
        for key in wanted + ["type", "integration_tests", "check_imports"]:
            value = str(pkg_cmds.get(key) or "")
            if value and value.upper() != "UNKNOWN" and value not in seen:
                seen.add(value)
                commands.append(f"{key}: `{value}`")
        if commands:
            # Package commands are usually the most relevant; do not flood.
            break

    root_cmds = c.get("commands") or {}
    for key in wanted:
        value = str(root_cmds.get(key) or "")
        if value and value.upper() != "UNKNOWN" and value not in seen:
            seen.add(value)
            commands.append(f"{key}: `{value}`")
    if not commands:
        commands.append("No reliable task command derived; run the nearest package/repo tests manually.")
    return commands[:8]


def _known_constraints(memory: Dict[str, Any]) -> List[str]:
    c = memory.get("agent_context") or {}
    out: List[str] = []
    for item in c.get("conventions") or []:
        out.append(f"Convention: {item}")
    for item in c.get("pitfalls") or []:
        out.append(str(item))
    confidence = c.get("derivation_confidence")
    if confidence:
        out.append(f"Repository memory confidence: {str(confidence).upper()}")
    graph = memory.get("graph_health") or ((c.get("graph_health") or {}).get("label") if isinstance(c.get("graph_health"), dict) else "")
    if graph:
        out.append(f"Graph health: {graph}")
    return list(dict.fromkeys(out))[:10]


def _dependency_notes(
    selected_paths: List[str],
    imports: Dict[str, Set[str]],
    imported_by: Dict[str, Set[str]],
) -> List[str]:
    selected = set(selected_paths)
    notes: List[str] = []
    for path in selected_paths[:10]:
        outs = sorted(p for p in imports.get(path, set()) if p in selected)
        ins = sorted(p for p in imported_by.get(path, set()) if p in selected)
        if outs:
            notes.append(f"`{path}` imports selected file(s): {', '.join(outs[:3])}")
        if ins:
            notes.append(f"`{path}` is imported by selected file(s): {', '.join(ins[:3])}")
        if not outs and not ins:
            near_out = sorted(imports.get(path, set()))[:2]
            near_in = sorted(imported_by.get(path, set()))[:2]
            if near_out:
                notes.append(f"`{path}` imports {', '.join(near_out)}")
            if near_in:
                notes.append(f"`{path}` has importer(s) {', '.join(near_in)}")
    return list(dict.fromkeys(notes))[:12]


def _confidence(selected: List[Candidate], signals: TaskSignals, graph_degraded: bool) -> Tuple[str, int, List[str]]:
    if not selected:
        return "LOW", 12, ["No relevant files selected."]
    top = selected[0].score
    components = set()
    for cand in selected[:5]:
        components.update(k for k, v in cand.components.items() if v > 0)
    reasons: List[str] = []
    if signals.files:
        reasons.append("Task mentioned file paths.")
    if "symbol" in components:
        reasons.append("Symbol index matched task terms.")
    if "dependency" in components:
        reasons.append("Dependency graph proximity contributed.")
    if "subsystem" in components or "package" in components:
        reasons.append("Repository memory subsystem/package evidence contributed.")
    if graph_degraded:
        reasons.append("Dependency graph is degraded, so graph-only evidence is capped.")

    score = min(95, int(round(top * 0.75 + len(components) * 5 + min(10, len(selected)))))
    if top >= 78 and len(components) >= 3 and not graph_degraded:
        label = "HIGH"
    elif top >= 52 and len(components) >= 2:
        label = "MEDIUM"
    else:
        label = "LOW"

    # Honest calibration: only the top file's own evidence justifies HIGH. A
    # unique strong anchor (direct mention, symbol-index, or canonical package
    # root) earns HIGH. When the winner is just a filename/keyword match AND
    # several other files score nearly as high, the result is ambiguous — many
    # similar candidates compete — so cap at MEDIUM rather than claim HIGH.
    strong = {"direct", "symbol", "canonical"}
    top_strong = any(selected[0].components.get(c, 0) > 0 for c in strong)
    crowded = sum(1 for c in selected[1:5] if top > 0 and c.score >= 0.85 * top)
    if label == "HIGH" and not top_strong and crowded >= 2:
        label = "MEDIUM"
        score = min(score, 72)
        reasons.append("Several similar files scored nearly as high; confidence capped.")

    if graph_degraded and label == "HIGH":
        label = "MEDIUM"
        score = min(score, 74)
    if top < 42:
        label = "LOW"
        score = min(score, 45)
    return label, max(0, min(100, score)), reasons[:6]


def _score_candidates(
    repo_path: str,
    task: str,
    *,
    state: Dict[str, Any],
    memory: Dict[str, Any],
) -> Tuple[TaskSignals, List[Candidate], List[Candidate], Dict[str, Any]]:
    signals = parse_task(task)
    index = state.get("index") or {}
    graph = state.get("graph") or {}
    scan = state.get("scan") or {}
    file_meta = {_norm_path(f.get("path", "")): f for f in index.get("files") or [] if f.get("path")}
    graph_paths = {
        _norm_path(n.get("path", ""))
        for n in graph.get("nodes") or []
        if n.get("type") == "module" and n.get("path")
    }
    all_paths = set(file_meta) | {p for p in graph_paths if p}
    candidates: Dict[str, Candidate] = {}
    imports, imported_by, fan_in, _fan_out = _graph_adjacency(graph)
    store = _load_store(state.get("evidence_store") or {})
    stem_counts = Counter(_stem(path) for path in all_paths if _stem(path))

    terms = _retrieval_terms(signals)
    content_terms = _content_terms(signals)

    # Direct file mentions.
    for mention in signals.files:
        for path in _resolve_file_mention(mention, all_paths):
            _candidate(candidates, path).add(90, f"directly mentioned `{mention}`", "direct")

    # Dotted module mentions.
    for module in signals.modules:
        module_l = module.lower()
        direct = False
        for path in all_paths:
            p_no_ext = os.path.splitext(path)[0].replace("/", ".").lower()
            if p_no_ext == module_l or p_no_ext.endswith("." + module_l):
                _candidate(candidates, path).add(72, f"module mention `{module}`", "direct")
                direct = True
        if not direct:
            for guess in _module_to_path_candidates(module):
                for path in _resolve_file_mention(guess, all_paths):
                    _candidate(candidates, path).add(60, f"module-like path for `{module}`", "direct")

    # Symbol index matches.
    if store:
        symbol_hits = []
        try:
            symbol_hits.extend(store.symbol_index.find_names(terms))
            symbol_hits.extend(store.symbol_index.find_in_source(terms[:18]))
        except Exception:
            symbol_hits = []
        seen_sym: Set[Tuple[str, str]] = set()
        by_file: Dict[str, List[Any]] = {}
        for sym in symbol_hits[:160]:
            key = (sym.file_path, sym.qualname or sym.name)
            if key in seen_sym:
                continue
            seen_sym.add(key)
            by_file.setdefault(sym.file_path, []).append(sym)
        for path, syms in by_file.items():
            names = [s.qualname or s.name for s in syms[:3]]
            usage = max((int(getattr(s, "usage_count", 0) or 0) for s in syms), default=0)
            amount = 24 + min(38, len(syms) * 7) + min(8, usage)
            _candidate(candidates, path).add(
                amount,
                f"symbol match: {', '.join(names)}",
                "symbol",
            )

    # Path/name matches across the indexed file list. This is not the only signal,
    # but it supplies recall for non-Python and symbol-index-capped repos.
    term_set = {t.lower().replace("_", "-") for t in terms if len(t) > 2}
    for path in all_paths:
        parts = _expanded_path_parts(path)
        base = os.path.basename(path).lower()
        stem = os.path.splitext(base)[0].lower()
        path_text = path.lower().replace("_", "-")
        hits = sorted(t for t in term_set if _term_matches_text(t, parts=parts, text=f"{base} {path_text}"))
        if hits:
            amount = min(56, 12 + len(hits) * 10)
            if len(hits) >= 3:
                amount += 8
            if any(stem in _term_variants(t) for t in hits):
                amount += 28
            if any(any(f"/{variant}/" in f"/{path.lower()}/" for variant in _term_variants(t)) for t in hits):
                amount += 12
            _candidate(candidates, path).add(amount, f"path/name matches {', '.join(hits[:4])}", "path")
            exact_hits = [t for t in hits if stem in _term_variants(t)]
            if exact_hits:
                _candidate(candidates, path).add(54, f"exact filename match {', '.join(exact_hits[:2])}", "exact")
            package_hits = _canonical_package_root_hits(path, hits)
            if package_hits:
                _candidate(candidates, path).add(
                    68,
                    f"canonical package root for {', '.join(package_hits[:2])}",
                    "canonical",
                )
            compound_hits = _compound_filename_hits(path, hits)
            if compound_hits:
                _candidate(candidates, path).add(
                    48,
                    f"compound filename matches {', '.join(compound_hits[:3])}",
                    "compound",
                )
        framework_boost, framework_reason = _framework_concept_boost(path, signals)
        if framework_boost:
            _candidate(candidates, path).add(framework_boost, framework_reason, "framework")
        # Soft morphological match: a stem contained in (or containing) a task
        # term, e.g. `query` <-> `queryset`. Lower weight than an exact hit so it
        # adds recall without overpowering precise matches.
        soft = sorted(set(_stem_related_terms(stem, term_set)) - set(hits))
        if soft:
            _candidate(candidates, path).add(
                min(30, 14 + len(soft) * 8),
                f"name related to {', '.join(soft[:3])}",
                "path",
            )

    # Bounded content evidence catches concepts that live in symbols/docstrings
    # whose files are outside the symbol-index cap. It is a supporting signal,
    # not the only retrieval mechanism.
    if content_terms:
        for path in all_paths:
            meta = file_meta.get(path, {})
            size = int(meta.get("size") or 0)
            if size <= 0 or size > 220_000:
                continue
            if not (_is_code_like_path(path) or _is_test_file_candidate(path)):
                continue
            text = _read_small_file(repo_path, path, max_chars=220_000).lower()
            if not text:
                continue
            hits = [term for term in content_terms if term.replace("-", "_") in text or term in text]
            if not hits:
                continue
            amount = min(58, 16 + len(hits) * 10)
            if any("_" in h for h in hits):
                amount += 7
            _candidate(candidates, path).add(amount, f"content mentions {', '.join(hits[:4])}", "content")

    # Repository-memory subsystems/packages/critical files.
    c = memory.get("agent_context") or {}
    for pkg in c.get("packages") or []:
        blob = " ".join([
            str(pkg.get("path") or ""),
            str(pkg.get("name") or ""),
            str(pkg.get("purpose") or ""),
            str(pkg.get("owner") or ""),
            " ".join(pkg.get("dependencies") or []),
        ]).lower()
        if any(t.replace("_", "-") in blob or t in blob for t in term_set):
            for path in pkg.get("representative_files") or []:
                _candidate(candidates, path).add(34, f"package `{pkg.get('path')}` matches task", "package")

    for sub in c.get("key_subsystems") or []:
        blob = " ".join([
            str(sub.get("name") or ""),
            str(sub.get("purpose") or ""),
            " ".join(sub.get("representative_files") or []),
        ]).lower()
        if any(t in blob for t in term_set):
            for path in sub.get("representative_files") or []:
                _candidate(candidates, path).add(24, f"subsystem `{sub.get('name')}` matches task", "subsystem")

    for path in c.get("critical_files") or []:
        cand = candidates.get(_norm_path(path))
        if cand:
            cand.add(10, "listed as important in repository memory", "importance")

    for hub in scan.get("top_hubs") or []:
        path = _norm_path(str(hub.get("path") or hub.get("module") or ""))
        if path and path in candidates:
            candidates[path].add(min(10, int(hub.get("fan_in") or 0)), "historical/import hub", "importance")

    for risk in scan.get("top_risks") or []:
        path = _norm_path(str(risk.get("path") or risk.get("module") or ""))
        if path and path in candidates:
            candidates[path].add(min(14, float(risk.get("score") or risk.get("risk_score") or 8)), "risk-ranked module", "risk")

    # Dependency proximity from strong anchors.
    anchors = [c.path for c in candidates.values() if c.score >= 40 and not _noise_reason(c.path)]
    for anchor in anchors[:12]:
        for dep in sorted(imports.get(anchor, set()))[:8]:
            _candidate(candidates, dep).add(18, f"imported by `{anchor}`", "dependency")
        for parent in sorted(imported_by.get(anchor, set()))[:8]:
            _candidate(candidates, parent).add(16, f"imports `{anchor}`", "dependency")

    # Test proximity. Keep tests available, but usually as Related tests.
    source_anchors = [p for p in anchors if not _is_test_path(p)]
    for src in source_anchors[:10]:
        stem = os.path.splitext(os.path.basename(src))[0].lower().replace("__init__", "")
        src_parts = set(_path_parts(src))
        for path in all_paths:
            if not _is_test_file_candidate(path):
                continue
            parts = set(_path_parts(path))
            if stem and stem in parts:
                _candidate(candidates, path).add(26, f"test near `{src}`", "test")
            elif src_parts and len(src_parts & parts) >= 2:
                _candidate(candidates, path).add(16, f"test shares path terms with `{src}`", "test")

    # Apply penalties and exclusions.
    excluded: List[Candidate] = []
    for cand in list(candidates.values()):
        meta = file_meta.get(cand.path, {})
        role = _file_role(cand.path, meta)
        noise = _noise_reason(cand.path)
        size = int(meta.get("size") or 0)
        if noise and "direct" not in cand.components:
            cand.score -= 42
            cand.excluded_reason = noise
        if _is_doc_path(cand.path) and "direct" not in cand.components:
            cand.score -= 16
            cand.excluded_reason = cand.excluded_reason or "documentation-only match"
        if role == "test_code" or _is_test_path(cand.path):
            if not (set(signals.actions) & {"test", "debug", "fix", "refactor"}):
                cand.score -= 10
        stem = _stem(cand.path)
        duplicate_leaf_count = stem_counts.get(stem, 0)
        if (
            duplicate_leaf_count >= 20
            and stem not in {"__init__", "base"}
            and _path_depth(cand.path) >= 4
            and "direct" not in cand.components
            and (stem in term_set or any(stem in _term_variants(t) for t in term_set))
        ):
            penalty = min(48, 18 + duplicate_leaf_count // 12)
            cand.score -= penalty
            cand.reasons.append(f"generic leaf penalty: {duplicate_leaf_count} `{stem}` files compete")
        if size > 300_000:
            cand.score -= 12
            cand.reasons.append("large file penalty")
        if cand.score < 24 or cand.excluded_reason:
            excluded.append(cand)

    ranked = [
        cnd for cnd in candidates.values()
        if cnd.score >= 24 and not cnd.excluded_reason and _norm_path(cnd.path) in all_paths
    ]
    ranked.sort(key=lambda cnd: (-cnd.score, cnd.path))
    excluded.sort(key=lambda cnd: (-cnd.score, cnd.path))
    graph_health = scan.get("graph_health") or {}
    graph_degraded = bool(scan.get("degraded"))
    if isinstance(graph_health, dict):
        graph_degraded = graph_degraded or bool(graph_health.get("degraded"))
        graph_degraded = graph_degraded or str(graph_health.get("label") or "").lower() == "degraded"
    else:
        graph_degraded = graph_degraded or str(graph_health).lower() == "degraded"
    meta = {
        "index_files": file_meta,
        "imports": imports,
        "imported_by": imported_by,
        "fan_in": fan_in,
        "store": store,
        "all_paths": all_paths,
        "graph_degraded": graph_degraded,
    }
    return signals, ranked, excluded[:_MAX_EXCLUDED], meta


def build_context_pack_from_state(
    repo_path: str,
    task: str,
    state: Dict[str, Any],
    *,
    memory: Optional[Dict[str, Any]] = None,
    include_snippets: bool = False,
    max_files: int = _DEFAULT_MAX_FILES,
) -> Dict[str, Any]:
    repo_path = os.path.abspath(repo_path)
    if memory is None:
        memory = state.get("repository_memory") or state.get("_current_memory")
    if not _usable_memory(memory, repo_path):
        memory = _repo_memory.build_memory(state, generated_by_version="context_pack")

    signals, ranked, excluded, meta = _score_candidates(repo_path, task, state=state, memory=memory)
    file_meta = meta["index_files"]
    imports = meta["imports"]
    imported_by = meta["imported_by"]
    store = meta["store"]

    # Recommended files: source/config files first; tests get their own section.
    selected_candidates: List[Candidate] = []
    related_test_candidates: List[Candidate] = []
    for cand in ranked:
        role = _file_role(cand.path, file_meta.get(cand.path, {}))
        if role == "test_code" or _is_test_path(cand.path):
            if not _is_test_file_candidate(cand.path):
                continue
            related_test_candidates.append(cand)
        elif len(selected_candidates) < max_files:
            selected_candidates.append(cand)
    # For explicit test/refactor tasks, allow a few tests in the main list too.
    if set(signals.actions) & {"test", "refactor"}:
        for cand in related_test_candidates[:3]:
            if cand not in selected_candidates and len(selected_candidates) < max_files:
                selected_candidates.append(cand)

    confidence, confidence_score, confidence_reasons = _confidence(
        selected_candidates, signals, bool(meta.get("graph_degraded"))
    )

    recommended: List[Dict[str, Any]] = []
    for cand in selected_candidates[:max_files]:
        rel = _norm_path(cand.path)
        meta_file = file_meta.get(rel, {})
        syms = []
        symbol_reason = ""
        if store:
            try:
                evs, _boost = file_symbol_evidence(store, rel, signals.concepts)
                syms = [ev.to_dict() for ev in evs[:4]]
                if evs:
                    symbol_reason = f"matched symbols: {', '.join(ev.qualname or ev.name for ev in evs[:3])}"
            except Exception:
                syms = []
        reasons = list(cand.reasons[:6])
        if symbol_reason and symbol_reason not in reasons:
            reasons.insert(0, symbol_reason)
        item = {
            "path": rel,
            "score": round(cand.score, 1),
            "role": _file_role(rel, meta_file),
            "subsystem": _subsystem_for_path(rel, memory, state.get("index") or {}),
            "reasons": reasons[:6],
            "components": dict(cand.components),
            "size_bytes": int(meta_file.get("size") or 0),
            "token_estimate": estimate_tokens(_read_small_file(repo_path, rel, max_chars=60_000)) if int(meta_file.get("size") or 0) <= 60_000 else estimate_tokens(""),
            "matched_symbols": syms,
        }
        if include_snippets:
            item["snippet"] = _snippet(repo_path, rel, signals.concepts)
        recommended.append(item)

    related_tests: List[Dict[str, Any]] = []
    for cand in related_test_candidates[:8]:
        related_tests.append({
            "path": cand.path,
            "score": round(cand.score, 1),
            "reasons": cand.reasons[:4],
            "subsystem": _subsystem_for_path(cand.path, memory, state.get("index") or {}),
        })

    selected_paths = [item["path"] for item in recommended]
    impacted = []
    for item in recommended + related_tests:
        sub = item.get("subsystem") or _subsystem_for_path(item["path"], memory, state.get("index") or {})
        if sub and sub not in impacted:
            impacted.append(sub)

    excluded_files = []
    for cand in excluded[:_MAX_EXCLUDED]:
        reason = cand.excluded_reason or "weak evidence after ranking"
        excluded_files.append({"path": cand.path, "reason": reason, "score": round(cand.score, 1)})

    dep_notes = _dependency_notes(selected_paths, imports, imported_by)
    commands = _commands_for_pack(recommended, signals, memory)
    constraints = _known_constraints(memory)

    pack = {
        "ok": True,
        "repo_path": repo_path,
        "repo_name": memory.get("repo_name") or os.path.basename(repo_path),
        "task": task,
        "task_signals": signals.to_dict(),
        "recommended_files": recommended,
        "related_tests": related_tests,
        "impacted_subsystems": impacted[:10],
        "relevant_commands": commands,
        "known_constraints": constraints,
        "dependency_notes": dep_notes,
        "excluded_files": excluded_files,
        "confidence": confidence,
        "confidence_score": confidence_score,
        "confidence_reasons": confidence_reasons,
        "token_estimate": 0,
        "include_snippets": include_snippets,
    }
    markdown = render_context_pack(pack)
    pack["markdown"] = markdown
    pack["token_estimate"] = estimate_tokens(markdown)
    return pack


def build_context_pack(
    repo_path: str,
    task: str,
    *,
    include_snippets: bool = False,
    max_files: int = _DEFAULT_MAX_FILES,
) -> Dict[str, Any]:
    """Scan a repository if needed and return a task-scoped context pack."""
    from . import api

    repo_path = os.path.abspath(repo_path)
    current = os.path.abspath(str(api._STATE.get("path") or ""))
    if current != repo_path or not api._STATE.get("scan"):
        scan = api.scan_repository(repo_path)
        if not scan.get("ok"):
            return {
                "ok": False,
                "repo_path": repo_path,
                "task": task,
                "error": scan.get("error") or "scan failed",
                "confidence": "LOW",
                "confidence_score": 0,
                "recommended_files": [],
                "excluded_files": [],
            }
    state = dict(api._STATE)
    memory = state.get("repository_memory") or state.get("_current_memory")
    if not _usable_memory(memory, repo_path):
        memory = _repo_memory.build_memory(state, generated_by_version="context_pack")
    return build_context_pack_from_state(
        repo_path,
        task,
        state,
        memory=memory,
        include_snippets=include_snippets,
        max_files=max_files,
    )


def render_context_pack(pack: Dict[str, Any]) -> str:
    lines: List[str] = ["# ATLAS_CONTEXT_PACK", ""]
    lines.append("## Task")
    lines.append(str(pack.get("task") or "").strip() or "UNKNOWN")

    lines.append("\n## Recommended files")
    recs = pack.get("recommended_files") or []
    if recs:
        for item in recs:
            lines.append(
                f"- `{item['path']}` ({item.get('role', 'unknown')}, score {item.get('score', 0)}): "
                + "; ".join((item.get("reasons") or ["selected by ranking"])[:3])
            )
    else:
        lines.append("- No relevant files identified with enough confidence.")

    lines.append("\n## Why these files")
    if recs:
        for item in recs[:12]:
            comps = ", ".join(sorted((item.get("components") or {}).keys())) or "heuristic"
            lines.append(f"- `{item['path']}`: evidence={comps}; subsystem={item.get('subsystem') or 'unknown'}.")
    else:
        lines.append("- Atlas did not find enough direct, symbol, path, subsystem, or dependency evidence.")

    lines.append("\n## Related tests")
    tests = pack.get("related_tests") or []
    if tests:
        for item in tests[:8]:
            lines.append(f"- `{item['path']}`: " + "; ".join((item.get("reasons") or ["test proximity"])[:2]))
    else:
        lines.append("- No closely related tests identified.")

    lines.append("\n## Impacted subsystems")
    subs = pack.get("impacted_subsystems") or []
    lines.append(", ".join(f"`{s}`" for s in subs) if subs else "UNKNOWN")

    lines.append("\n## Relevant commands")
    for cmd in pack.get("relevant_commands") or []:
        lines.append(f"- {cmd}")

    lines.append("\n## Known constraints")
    constraints = pack.get("known_constraints") or []
    if constraints:
        for item in constraints:
            lines.append(f"- {item}")
    else:
        lines.append("- No repository-memory constraints identified.")

    lines.append("\n## Dependency notes")
    notes = pack.get("dependency_notes") or []
    if notes:
        for note in notes:
            lines.append(f"- {note}")
    else:
        lines.append("- No selected-file dependency links identified.")

    lines.append("\n## Excluded files")
    excluded = pack.get("excluded_files") or []
    if excluded:
        for item in excluded[:_MAX_EXCLUDED]:
            lines.append(f"- `{item['path']}`: {item.get('reason') or 'likely irrelevant'}")
    else:
        lines.append("- No notable exclusions.")

    if pack.get("include_snippets"):
        snippets = [(item["path"], item.get("snippet")) for item in recs if item.get("snippet")]
        lines.append("\n## Snippets")
        if snippets:
            for path, snippet in snippets[:5]:
                lines.append(f"### `{path}`")
                lines.append("```text")
                lines.append(str(snippet).strip())
                lines.append("```")
        else:
            lines.append("- No snippets matched requested symbols/terms.")

    lines.append("\n## Confidence")
    lines.append(f"{pack.get('confidence', 'LOW')} ({pack.get('confidence_score', 0)}/100)")
    for reason in pack.get("confidence_reasons") or []:
        lines.append(f"- {reason}")

    lines.append("\n## Token estimate")
    lines.append(str(pack.get("token_estimate") or estimate_tokens("\n".join(lines))))
    return "\n".join(lines).strip() + "\n"


def write_context_pack(
    repo_path: str,
    task: str,
    *,
    output_path: Optional[str] = None,
    include_snippets: bool = False,
    max_files: int = _DEFAULT_MAX_FILES,
) -> Dict[str, Any]:
    pack = build_context_pack(
        repo_path,
        task,
        include_snippets=include_snippets,
        max_files=max_files,
    )
    if not pack.get("ok"):
        return pack
    out = output_path or os.path.join(os.path.abspath(repo_path), "ATLAS_CONTEXT_PACK.md")
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(pack["markdown"])
    pack["output_path"] = os.path.abspath(out)
    return pack
