"""Shared type definitions."""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Intent(str, Enum):
    """Allowed command intents."""

    OPEN_CURSOR = "open_cursor"
    OPEN_CHROME = "open_chrome"
    OPEN_FILE_EXPLORER = "open_file_explorer"
    OPEN_TERMINAL = "open_terminal"
    OPEN_TASK_MANAGER = "open_task_manager"
    OPEN_TRADING_DASHBOARD = "open_trading_dashboard"
    OPEN_TRADING_DASHBOARD_URL = "open_trading_dashboard_url"
    RUN_LIVE_DAILY_LOOP = "run_live_daily_loop"
    RUN_LIVE_WEEKLY_LOOP = "run_live_weekly_loop"
    STOP_TRADING_LOOP = "stop_trading_loop"
    SHOW_LATEST_LIVE_REPORT = "show_latest_live_report"
    SHOW_OPEN_POSITIONS = "show_open_positions"
    SHOW_LAST_ERRORS = "show_last_errors"
    SHOW_DASHBOARD_HEALTH = "show_dashboard_health"
    SHOW_RECENT_TRADING_HISTORY = "show_recent_trading_history"
    SHOW_REJECTION_REASONS = "show_rejection_reasons"
    SHOW_BLOCKED_TRADES = "show_blocked_trades"
    SEARCH_TRADING_LOGS = "search_trading_logs"
    ENABLE_KILL_SWITCH = "enable_kill_switch"
    DISABLE_KILL_SWITCH = "disable_kill_switch"
    OPEN_PROJECT_FOLDER = "open_project_folder"
    OPEN_LATEST_LOG = "open_latest_log"
    SUMMARIZE_LATEST_LOG = "summarize_latest_log"
    SEARCH_PROJECT_FILE_BY_NAME = "search_project_file_by_name"
    SEARCH_CODE_TEXT = "search_code_text"
    FIND_FUNCTION = "find_function"
    FIND_CLASS = "find_class"
    FIND_CONFIG_KEY = "find_config_key"
    FIND_RISK_USAGE = "find_risk_usage"
    FIND_DELAYED_ENTRY_LOGIC = "find_delayed_entry_logic"
    FIND_EXECUTION_EVENTS_LOGIC = "find_execution_events_logic"
    SHOW_CPU_RAM_USAGE = "show_cpu_ram_usage"
    SHOW_DISK_USAGE = "show_disk_usage"
    SHOW_NETWORK_STATUS = "show_network_status"
    SHOW_SYSTEM_STATUS = "show_system_status"
    SHUTDOWN_JARVIS = "shutdown_jarvis"
    SHOW_CAPABILITIES = "show_capabilities"
    LIST_SKILLS = "list_skills"
    EXPLAIN_SKILL = "explain_skill"
    HELP_FOR_COMMAND = "help_for_command"
    REMEMBER_PREFERENCE = "remember_preference"
    REMEMBER_FACT = "remember_fact"
    FORGET_MEMORY = "forget_memory"
    LIST_MEMORY = "list_memory"
    SHOW_MEMORY_DEBUG = "show_memory_debug"
    SEARCH_MEMORY = "search_memory"
    REMEMBER_THIS = "remember_this"
    SHOW_MEMORY = "show_memory"
    INDEX_PROJECT = "index_project"
    SEARCH_PROJECT_KNOWLEDGE = "search_project_knowledge"
    SHOW_MEMORY_GRAPH = "show_memory_graph"
    SEARCH_MEMORY_GRAPH = "search_memory_graph"
    SET_ALIAS = "set_alias"
    DELETE_ALIAS = "delete_alias"
    LIST_ALIASES = "list_aliases"
    SET_PREFERENCE = "set_preference"
    LIST_PREFERENCES = "list_preferences"
    FORGET_PREFERENCE = "forget_preference"
    DESCRIBE_SCREEN = "describe_screen"
    READ_SCREEN_TEXT = "read_screen_text"
    ANALYZE_ACTIVE_WINDOW = "analyze_active_window"
    FIND_ON_SCREEN = "find_on_screen"
    DETECT_SCREEN_ERRORS = "detect_screen_errors"
    GET_ACTIVE_WINDOW = "get_active_window"
    TAKE_SCREENSHOT = "take_screenshot"
    LIST_VISIBLE_WINDOWS = "list_visible_windows"
    RUN_DIAGNOSTICS = "run_diagnostics"
    DIAGNOSE_DASHBOARD = "diagnose_dashboard"
    DIAGNOSE_TRADING_LOOP = "diagnose_trading_loop"
    DIAGNOSE_RECENT_ERRORS = "diagnose_recent_errors"
    ANALYZE_CURRENT_SCREEN = "analyze_current_screen"
    EXPLAIN_LAST_FAILURE = "explain_last_failure"
    SUGGEST_NEXT_STEPS = "suggest_next_steps"
    LIST_WORKFLOWS = "list_workflows"
    RUN_WORKFLOW = "run_workflow"
    EXPLAIN_WORKFLOW = "explain_workflow"
    ENABLE_AUTOSTART = "enable_autostart"
    DISABLE_AUTOSTART = "disable_autostart"
    SHOW_AUTOSTART_STATUS = "show_autostart_status"
    RUN_JARVIS_HEALTH_CHECK = "run_jarvis_health_check"
    SHOW_WATCHDOG_STATUS = "show_watchdog_status"
    GET_FOCUSED_APP = "get_focused_app"
    LIST_WINDOWS_DETAILED = "list_windows_detailed"
    GET_CLIPBOARD_SUMMARY = "get_clipboard_summary"
    FOCUS_WINDOW = "focus_window"
    COPY_TEXT_TO_CLIPBOARD = "copy_text_to_clipboard"
    CLEAR_CLIPBOARD = "clear_clipboard"
    MINIMIZE_WINDOW = "minimize_window"
    MAXIMIZE_WINDOW = "maximize_window"
    SHOW_STT_STATUS = "show_stt_status"
    BENCHMARK_STT = "benchmark_stt"
    SHOW_TTS_STATUS = "show_tts_status"
    SHOW_TTS_DEBUG = "show_tts_debug"
    TEST_TTS_PLAYBACK = "test_tts_playback"
    TEST_DIRECT_TTS = "test_direct_tts"
    TEST_STREAMING_STT = "test_streaming_stt"
    SHOW_VOICE_DEBUG = "show_voice_debug"
    SHOW_AUDIO_STATUS = "show_audio_status"
    TOOL_MODE_STATUS = "tool_mode_status"
    TEST_VOICE_OUTPUT = "test_voice_output"
    SHOW_WAKE_DIAGNOSTICS = "show_wake_diagnostics"
    SHOW_AUDIO_DEVICES = "show_audio_devices"
    TEST_LEFT_CHANNEL = "test_left_channel"
    TEST_RIGHT_CHANNEL = "test_right_channel"
    TEST_AUDIO_ROUTING = "test_audio_routing"
    CYCLE_AUDIO_OUTPUT = "cycle_audio_output"
    SHOW_WINDOWS_AUDIO_ROUTING = "show_windows_audio_routing"
    CYCLE_WINDOWS_PLAYBACK_TARGET = "cycle_windows_playback_target"
    CALIBRATE_VOICE = "calibrate_voice"
    DIAGNOSE_VOICE_RUNTIME = "diagnose_voice_runtime"
    RESET_JARVIS_RUNTIME = "reset_jarvis_runtime"
    SHOW_RUNTIME_STATUS = "show_runtime_status"
    SHOW_LATENCY_STATUS = "show_latency_status"
    SHOW_VOICE_PERFORMANCE_STATUS = "show_voice_performance_status"
    DISCOVER_APPS = "discover_apps"
    LIST_APPS = "list_apps"
    SEARCH_APPS = "search_apps"
    OPEN_APP = "open_app"
    APPROVE_APP = "approve_app"
    FORGET_APP = "forget_app"
    LIST_WEBSITES = "list_websites"
    OPEN_WEBSITE = "open_website"
    OPEN_BROWSER = "open_browser"
    SEARCH_WEB_FOR = "search_web_for"
    FIND_INFORMATION_ABOUT = "find_information_about"
    OPEN_BEST_RESULT = "open_best_result"
    SUMMARIZE_TOP_RESULTS = "summarize_top_results"
    COMPARE_THESE_SEARCH_RESULTS = "compare_these_search_results"
    EXTRACT_KEY_FACTS_FROM_THIS_PAGE = "extract_key_facts_from_this_page"
    SAVE_BROWSER_RESEARCH_REPORT = "save_browser_research_report"
    SUMMARIZE_THIS_PAGE = "summarize_this_page"
    COMPARE_THESE_RESULTS = "compare_these_results"
    COMPARE_THESE_PAGES = "compare_these_pages"
    WHAT_TAB_IS_ACTIVE = "what_tab_is_active"
    TEST_REAL_BROWSER = "test_real_browser"
    TEST_REAL_VOICE_CONVERSATION = "test_real_voice_conversation"
    SHOW_DESKTOP_VISION_HEALTH = "show_desktop_vision_health"
    ALPHA_SETUP_CHECK = "alpha_setup_check"
    SHOW_ALPHA_REPORT = "show_alpha_report"
    SHOW_BROWSER_DEBUG = "show_browser_debug"
    APPROVE_WEBSITE = "approve_website"
    FORGET_WEBSITE = "forget_website"
    START_TASK = "start_task"
    SHOW_TASK_PLAN = "show_task_plan"
    APPROVE_TASK_PLAN = "approve_task_plan"
    RUN_TASK_STEP = "run_task_step"
    STOP_TASK = "stop_task"
    SHOW_TASK_STATUS = "show_task_status"
    SHOW_TASK_REPORT = "show_task_report"
    SHOW_TASK_FINDINGS = "show_task_findings"
    PROPOSE_TASK_PATCH = "propose_task_patch"
    SHOW_TASK_PATCH = "show_task_patch"
    APPROVE_TASK_PATCH = "approve_task_patch"
    REJECT_TASK_PATCH = "reject_task_patch"
    APPLY_TASK_PATCH = "apply_task_patch"
    ROLLBACK_TASK_PATCH = "rollback_task_patch"
    SHOW_LAST_DIFF = "show_last_diff"
    REVIEW_TRADING_ALGORITHM = "review_trading_algorithm"
    COMPARE_BACKTEST_TO_PAPER = "compare_backtest_to_paper"
    FIND_LIVE_BACKTEST_MISMATCH = "find_live_backtest_mismatch"
    GENERATE_BACKTEST_PAPER_REPORT = "generate_backtest_paper_report"
    PLAN_EXPERIMENTS = "plan_experiments"
    QUEUE_TASK = "queue_task"
    SHOW_TASK_QUEUE = "show_task_queue"
    PAUSE_TASK_QUEUE = "pause_task_queue"
    RESUME_TASK_QUEUE = "resume_task_queue"
    START_TRADING_WORKSPACE = "start_trading_workspace"
    START_STUDY_WORKSPACE = "start_study_workspace"
    START_DEV_WORKSPACE = "start_dev_workspace"
    SUGGEST_UI_CLICK = "suggest_ui_click"
    CONFIRM_UI_CLICK = "confirm_ui_click"
    BROWSER_DOM_READ = "browser_dom_read"
    BUILD_PRESENTATION = "build_presentation"
    CREATE_REPORT_DOCUMENT = "create_report_document"
    SHOW_STARTUP_HEALTH = "show_startup_health"
    SHOW_SETTINGS_STATUS = "show_settings_status"
    SHOW_JARVIS_STATUS = "show_jarvis_status"
    SHOW_COMMAND_AUDIT = "show_command_audit"
    SHOW_APPROVALS = "show_approvals"
    APPROVE_PENDING_ACTION = "approve_pending_action"
    REJECT_PENDING_ACTION = "reject_pending_action"
    CLEAR_APPROVALS = "clear_approvals"
    SHOW_OVERLAY = "show_overlay"
    HIDE_OVERLAY = "hide_overlay"
    TOGGLE_QUIET_MODE = "toggle_quiet_mode"
    WHAT_AM_I_DOING = "what_am_i_doing"
    REVIEW_LATEST_PATCH = "review_latest_patch"
    SUMMARIZE_RECENT_CHANGES = "summarize_recent_changes"
    SHOW_FAILING_TESTS = "show_failing_tests"
    SUMMARIZE_THIS_FILE = "summarize_this_file"
    SHOW_RECENT_COMMANDS = "show_recent_commands"
    EXPLAIN_THIS_ERROR = "explain_this_error"
    START_STUDY_MODE = "start_study_mode"
    FOCUS_MODE = "focus_mode"
    SUMMARIZE_MY_NOTES = "summarize_my_notes"
    EXPLAIN_THIS_CODE = "explain_this_code"
    QUIZ_ME = "quiz_me"
    WHAT_SHOULD_I_STUDY_NEXT = "what_should_i_study_next"
    ASSISTANT_EXPLAIN = "assistant_explain"
    ASSISTANT_PLAN = "assistant_plan"
    WHAT_WERE_WE_DOING = "what_were_we_doing"
    SUMMARIZE_SESSION = "summarize_session"
    SWITCH_VOICE = "switch_voice"
    LIST_VOICES = "list_voices"
    SET_FEMALE_VOICE = "set_female_voice"
    SET_CINEMATIC_VOICE = "set_cinematic_voice"
    SET_VOICE_EMOTION = "set_voice_emotion"
    BENCHMARK_TTS = "benchmark_tts"
    STOP_SPEAKING = "stop_speaking"
    STOP_SPEECH_HARD = "stop_speech_hard"
    LIST_STT_ENGINES = "list_stt_engines"
    SHOW_STT_STACK_STATUS = "show_stt_stack_status"
    AUTO_TUNE_VOICE = "auto_tune_voice"
    TEST_DIRECT_SPEECH = "test_direct_speech"
    VERIFY_DIRECT_SPEECH_BACKEND = "verify_direct_speech_backend"
    FORCE_VERIFIED_DIRECT_SPEECH = "force_verified_direct_speech"
    TEST_NORMAL_SPEECH = "test_normal_speech"
    AUDIO_ROUTE_PROVE = "audio_route_prove"
    FORCE_DIRECT_PYTTSX3_NORMAL_MODE = "force_direct_pyttsx3_normal_mode"
    TEST_SUBPROCESS_SPEECH = "test_subprocess_speech"
    FORCE_SHELL_TTS_TEST = "force_shell_tts_test"
    VOICE_SMOKE_TEST = "voice_smoke_test"
    FOUNDATION_HEALTH_CHECK = "foundation_health_check"
    SHOW_LAUNCHER_STATUS = "show_launcher_status"
    SHOW_CONTROL_STATUS = "show_control_status"
    SHOW_SCREEN_STATUS = "show_screen_status"
    SHOW_RUNTIME_THREADS = "show_runtime_threads"
    BENCHMARK_VOICE_MODES = "benchmark_voice_modes"
    SHOW_TTS_THREADS = "show_tts_threads"
    PHASE45_STATUS = "phase45_status"
    PHASE46_STATUS = "phase46_status"
    INSPECT_PROJECT = "inspect_project"
    INSPECT_WEBSITE_PROJECT = "inspect_website_project"
    SUMMARIZE_CURRENT_PROJECT = "summarize_current_project"
    FIND_FAILING_TESTS = "find_failing_tests"
    EXPLAIN_LATEST_ERROR = "explain_latest_error"
    INVESTIGATE_TRADING_MISMATCH = "investigate_trading_mismatch"
    COMPARE_LIVE_VS_BACKTEST = "compare_live_vs_backtest"
    INSPECT_LATEST_LIVE_REPORT = "inspect_latest_live_report"
    INSPECT_LATEST_BACKTEST_REPORT = "inspect_latest_backtest_report"
    FIND_RECENT_CODE_CHANGES = "find_recent_code_changes"
    PROPOSE_INVESTIGATION_PLAN = "propose_investigation_plan"
    RUN_SAFE_DIAGNOSTICS = "run_safe_diagnostics"
    GENERATE_FINDINGS_REPORT = "generate_findings_report"
    BUILD_INVESTIGATION_GRAPH = "build_investigation_graph"
    SHOW_INVESTIGATION_GRAPH = "show_investigation_graph"
    SEARCH_INVESTIGATION_GRAPH = "search_investigation_graph"
    TRACE_ALGORITHM_BEHAVIOR = "trace_algorithm_behavior"
    DIFF_LIVE_BACKTEST_LOGIC = "diff_live_backtest_logic"
    HUNT_ALGORITHM_BUGS = "hunt_algorithm_bugs"
    PROPOSE_ALGORITHM_PATCH = "propose_algorithm_patch"
    PLAN_VERIFICATION_RUN = "plan_verification_run"
    REPLAY_SYMBOL = "replay_symbol"
    REPLAY_LATEST_SIGNAL = "replay_latest_signal"
    REPLAY_LIVE_VS_BACKTEST = "replay_live_vs_backtest"
    VERIFY_TOP_HYPOTHESIS = "verify_top_hypothesis"
    VERIFY_ALL_HYPOTHESES = "verify_all_hypotheses"
    SHOW_REPLAY_TIMELINE = "show_replay_timeline"
    SHOW_REPLAY_DIFF = "show_replay_diff"
    BUILD_VERIFICATION_FIXTURE = "build_verification_fixture"
    EXPORT_REPLAY_SNAPSHOT = "export_replay_snapshot"
    TRACE_SIGNAL_LIFECYCLE = "trace_signal_lifecycle"
    TRACE_EXECUTION_LIFECYCLE = "trace_execution_lifecycle"
    SHOW_CAUSALITY_GRAPH = "show_causality_graph"
    INVESTIGATION_CONFIDENCE_REPORT = "investigation_confidence_report"
    SIMULATE_PATCH_TOP_HYPOTHESIS = "simulate_patch_top_hypothesis"
    RUN_PATCH_SIMULATION = "run_patch_simulation"
    COMPARE_REPLAY_BEFORE_AFTER = "compare_replay_before_after"
    ESTIMATE_PATCH_IMPACT = "estimate_patch_impact"
    GENERATE_PATCH_SIMULATION_REPORT = "generate_patch_simulation_report"
    SHOW_PATCH_SIMULATION = "show_patch_simulation"
    APPROVE_PATCH_APPLY = "approve_patch_apply"
    REJECT_PATCH_APPLY = "reject_patch_apply"
    RUN_HISTORICAL_VALIDATION_SWEEP = "run_historical_validation_sweep"
    SHOW_VALIDATION_SWEEP = "show_validation_sweep"
    EXPORT_VALIDATION_SWEEP = "export_validation_sweep"
    COMPARE_STRATEGY_METRICS_BEFORE_AFTER = "compare_strategy_metrics_before_after"
    SHOW_WORST_DIVERGENCE_SYMBOLS = "show_worst_divergence_symbols"
    ESTIMATE_PRODUCTION_RISK = "estimate_production_risk"
    RECOMMEND_PRODUCTION_ACTION = "recommend_production_action"
    SHOW_INVESTIGATION_SUMMARY = "show_investigation_summary"
    AUDIT_PRICE_INTEGRITY = "audit_price_integrity"
    COMPARE_CANDLE_SOURCES = "compare_candle_sources"
    TRACE_PRICE_SOURCE = "trace_price_source"
    FIND_CLOSE_PRICE_MISMATCHES = "find_close_price_mismatches"
    INSPECT_DATA_CACHE_DRIFT = "inspect_data_cache_drift"
    CHECK_TIMESTAMP_ALIGNMENT = "check_timestamp_alignment"
    CHECK_ADJUSTED_PRICE_USAGE = "check_adjusted_price_usage"
    CHECK_DUPLICATE_BARS = "check_duplicate_bars"
    GENERATE_PRICE_INTEGRITY_REPORT = "generate_price_integrity_report"
    AUDIT_EXECUTION_PATH = "audit_execution_path"
    EXPLAIN_ZERO_EXECUTION_ATTEMPTS = "explain_zero_execution_attempts"
    TRACE_SIGNAL_TO_ORDER = "trace_signal_to_order"
    SHOW_EXECUTION_BLOCKERS = "show_execution_blockers"
    RANK_EXECUTION_BLOCK_REASONS = "rank_execution_block_reasons"
    INSPECT_EXECUTION_ADAPTER = "inspect_execution_adapter"
    COMPARE_SIGNAL_COUNT_TO_ORDER_ATTEMPTS = "compare_signal_count_to_order_attempts"
    GENERATE_EXECUTION_INVESTIGATION_REPORT = "generate_execution_investigation_report"
    TRACE_SIGNAL_TO_EXECUTION = "trace_signal_to_execution"
    TRACE_BLOCKED_SIGNAL = "trace_blocked_signal"
    EXPLAIN_TOP_EXECUTION_BLOCKER = "explain_top_execution_blocker"
    RECONSTRUCT_EXECUTION_FLOW = "reconstruct_execution_flow"
    SHOW_SIGNAL_LIFECYCLE_TIMELINE = "show_signal_lifecycle_timeline"
    RANK_DEAD_SIGNAL_CAUSES = "rank_dead_signal_causes"
    SIMULATE_UNBLOCK_SCENARIO = "simulate_unblock_scenario"
    PROPOSE_EXECUTION_FIX = "propose_execution_fix"
    GENERATE_EXECUTION_FLOW_REPORT = "generate_execution_flow_report"
    SIMULATE_EXECUTION_CLEANUP_PATCH = "simulate_execution_cleanup_patch"
    COMPARE_RISK_BEFORE_AFTER_CLEANUP = "compare_risk_before_after_cleanup"
    SHOW_STALE_OPEN_POSITIONS = "show_stale_open_positions"
    PROPOSE_EXECUTION_CLEANUP_PATCH = "propose_execution_cleanup_patch"
    GENERATE_EXECUTION_CLEANUP_REPORT = "generate_execution_cleanup_report"
    SHOW_APPROVED_PATCH = "show_approved_patch"
    VALIDATE_PATCH_SAFETY = "validate_patch_safety"
    APPLY_APPROVED_PATCH = "apply_approved_patch"
    ROLLBACK_LAST_PATCH = "rollback_last_patch"
    SHOW_PATCH_HISTORY = "show_patch_history"
    VALIDATE_APPLIED_PATCH = "validate_applied_patch"
    REPLAY_AFTER_PATCH = "replay_after_patch"
    COMPARE_PRE_POST_PATCH = "compare_pre_post_patch"
    RUN_PATCH_WORKFLOW = "run_patch_workflow"
    SHOW_PATCH_WORKFLOW_STATUS = "show_patch_workflow_status"
    # Phase 49 — operational healing
    SHOW_RUNTIME_HEALTH = "show_runtime_health"
    SHOW_HEALING_ACTIONS = "show_healing_actions"
    SHOW_STUCK_WORKERS = "show_stuck_workers"
    RESTART_FAILED_WORKER = "restart_failed_worker"
    CLEAR_STALE_LOCKS = "clear_stale_locks"
    RECOVER_OVERLAY = "recover_overlay"
    RECOVER_VOICE_SYSTEM = "recover_voice_system"
    RESTART_DASHBOARD = "restart_dashboard"
    RESTART_WAKE_LISTENER = "restart_wake_listener"
    RESTART_OPERATOR_CONSOLE = "restart_operator_console"
    VALIDATE_RUNTIME_INTEGRITY = "validate_runtime_integrity"
    PHASE49_STATUS = "phase49_status"
    # Phase 50 — desktop + context memory
    WHAT_AM_I_LOOKING_AT = "what_am_i_looking_at"
    SUMMARIZE_CURRENT_SCREEN = "summarize_current_screen"
    SUMMARIZE_TRADING_HEALTH = "summarize_trading_health"
    EXPLAIN_WHY_NO_TRADES_TODAY = "explain_why_no_trades_today"
    COMPARE_TODAY_VS_YESTERDAY = "compare_today_vs_yesterday"
    SHOW_TOP_OPERATIONAL_BLOCKERS = "show_top_operational_blockers"
    SHOW_CURRENT_EXECUTION_RISK = "show_current_execution_risk"
    SUMMARIZE_LIVE_ENGINE_STATUS = "summarize_live_engine_status"
    RESUME_LAST_TASK = "resume_last_task"
    SHOW_RECENT_INVESTIGATIONS = "show_recent_investigations"
    CONTINUE_INVESTIGATION = "continue_investigation"
    OPEN_LAST_REPORT = "open_last_report"
    SEARCH_REPORTS = "search_reports"
    SHOW_CURRENT_STATE = "show_current_state"
    SHOW_ACTIVE_SYSTEMS = "show_active_systems"
    SHOW_RUNTIME_SUMMARY = "show_runtime_summary"
    SHOW_OPERATIONAL_SUGGESTIONS = "show_operational_suggestions"
    PHASE50_STATUS = "phase50_status"
    # Phase 51 — desktop awareness + reliability
    SHOW_OPEN_WINDOWS = "show_open_windows"
    SHOW_SCREEN_SYSTEM_STATUS = "show_screen_system_status"
    SHOW_FOCUSED_WINDOW = "show_focused_window"
    SWITCH_TO_BROWSER = "switch_to_browser"
    SWITCH_TO_CURSOR = "switch_to_cursor"
    SWITCH_TO_DASHBOARD = "switch_to_dashboard"
    FOCUS_TERMINAL = "focus_terminal"
    SHOW_MEMORY_STATE = "show_memory_state"
    CLEAR_COMPLETED_TASK = "clear_completed_task"
    PIN_INVESTIGATION = "pin_investigation"
    CONTINUE_TRADING_INVESTIGATION = "continue_trading_investigation"
    SHOW_TRADING_OPERATIONS_DASHBOARD = "show_trading_operations_dashboard"
    # Phase 63 — desktop operator runtime
    WHAT_IS_ON_MY_SCREEN = "what_is_on_my_screen"
    SUMMARIZE_THIS_SCREEN = "summarize_this_screen"
    CLICK_BUTTON_THAT_SAYS = "click_button_that_says"
    TYPE_THIS = "type_this"
    SWITCH_TO_CHROME = "switch_to_chrome"
    LIST_OPEN_WINDOWS = "list_open_windows"
    # Phase 65 — product hardening
    SHOW_VOICE_HEALTH = "show_voice_health"
    REPAIR_MEMORY_STORE = "repair_memory_store"
    SHOW_BROWSER_HEALTH = "show_browser_health"
    SHOW_DESKTOP_OPERATOR_HEALTH = "show_desktop_operator_health"
    SHOW_SYSTEM_HEALTH = "show_system_health"
    SHOW_PERFORMANCE_REPORT = "show_performance_report"
    SUMMARIZE_MY_INBOX = "summarize_my_inbox"
    SHOW_URGENT_EMAILS = "show_urgent_emails"
    SUMMARIZE_MY_CALENDAR = "summarize_my_calendar"
    GENERATE_PRODUCT_READINESS_REPORT = "generate_product_readiness_report"
    # Phase 52 — result streaming + background tasks
    SHOW_RUNNING_TASKS = "show_running_tasks"
    CANCEL_TASK = "cancel_task"
    SHOW_COMPLETED_TASKS = "show_completed_tasks"
    SHOW_FAILED_TASKS = "show_failed_tasks"
    RERUN_LAST_BACKGROUND_TASK = "rerun_last_background_task"
    SHOW_RECENT_RESULTS = "show_recent_results"
    SHOW_NOTIFICATIONS = "show_notifications"
    CLEAR_NOTIFICATIONS = "clear_notifications"
    EXPLAIN_LAST_RESULT = "explain_last_result"
    # Phase 53 — persistent assistant state
    REOPEN_TASK_RESULT = "reopen_task_result"
    ARCHIVE_NOTIFICATION = "archive_notification"
    EXPLAIN_NOTIFICATION = "explain_notification"
    CONTINUE_PREVIOUS_SESSION = "continue_previous_session"
    SUMMARIZE_UNRESOLVED_ISSUES = "summarize_unresolved_issues"
    RESUME_LATEST_INVESTIGATION = "resume_latest_investigation"
    WHAT_CHANGED_SINCE_LAST_SESSION = "what_changed_since_last_session"
    SUMMARIZE_SYSTEM_INTELLIGENCE = "summarize_system_intelligence"
    SUMMARIZE_UNRESOLVED_BLOCKERS = "summarize_unresolved_blockers"
    EXPLAIN_CURRENT_OPERATIONAL_STATE = "explain_current_operational_state"
    RECOMMEND_NEXT_ACTION = "recommend_next_action"
    WHAT_SHOULD_WE_INVESTIGATE_NEXT = "what_should_we_investigate_next"
    # Phase 54 — autonomous investigation loops
    SHOW_INVESTIGATION_SCHEDULE = "show_investigation_schedule"
    RUN_INVESTIGATION_CYCLE = "run_investigation_cycle"
    PAUSE_INVESTIGATION_LOOP = "pause_investigation_loop"
    RESUME_INVESTIGATION_LOOP = "resume_investigation_loop"
    RUN_NIGHTLY_INVESTIGATION_NOW = "run_nightly_investigation_now"
    SHOW_BLOCKER_TRENDS = "show_blocker_trends"
    COMPARE_BLOCKER_TRENDS = "compare_blocker_trends"
    EXPLAIN_DOMINANT_BLOCKER = "explain_dominant_blocker"
    SHOW_BLOCKER_HISTORY = "show_blocker_history"
    CLUSTER_REPLAY_DIVERGENCES = "cluster_replay_divergences"
    SHOW_DIVERGENCE_CLUSTERS = "show_divergence_clusters"
    EXPLAIN_LARGEST_DIVERGENCE_CLUSTER = "explain_largest_divergence_cluster"
    SHOW_ACTIVE_HYPOTHESES = "show_active_hypotheses"
    VERIFY_ACTIVE_HYPOTHESES = "verify_active_hypotheses"
    EXPLAIN_AUTONOMOUS_TOP_HYPOTHESIS = "explain_autonomous_top_hypothesis"
    COMPARE_HYPOTHESIS_HISTORY = "compare_hypothesis_history"
    SHOW_INTELLIGENCE_TIMELINE = "show_intelligence_timeline"
    EXPLAIN_RECENT_ANOMALIES = "explain_recent_anomalies"
    COMPARE_TODAY_VS_YESTERDAY_INTELLIGENCE = "compare_today_vs_yesterday_intelligence"
    SUMMARIZE_AUTONOMOUS_FINDINGS = "summarize_autonomous_findings"
    SUMMARIZE_OPERATIONAL_ANOMALIES = "summarize_operational_anomalies"
    EXPLAIN_CURRENT_TRADING_RISK = "explain_current_trading_risk"
    # Phase 55 — autonomous root cause verification
    SHOW_VERIFICATION_PLANS = "show_verification_plans"
    EXPLAIN_VERIFICATION_PLAN = "explain_verification_plan"
    RUN_VERIFICATION_PLAN = "run_verification_plan"
    VERIFY_ROOT_CAUSES = "verify_root_causes"
    SHOW_CONFIDENCE_EVOLUTION = "show_confidence_evolution"
    EXPLAIN_CONFIDENCE_CHANGES = "explain_confidence_changes"
    COMPARE_ROOT_CAUSE_CONFIDENCE = "compare_root_cause_confidence"
    SHOW_CONTRADICTORY_EVIDENCE = "show_contradictory_evidence"
    EXPLAIN_CONTRADICTION = "explain_contradiction"
    RESOLVE_CONTRADICTION = "resolve_contradiction"
    SUGGEST_EXPERIMENTS = "suggest_experiments"
    EXPLAIN_EXPERIMENT_IMPACT = "explain_experiment_impact"
    RUN_SAFE_EXPERIMENT_SIMULATION = "run_safe_experiment_simulation"
    SHOW_ROOT_CAUSE_GRAPH = "show_root_cause_graph"
    EXPLAIN_ROOT_CAUSE_GRAPH = "explain_root_cause_graph"
    TRACE_CAUSAL_CHAIN = "trace_causal_chain"
    SUMMARIZE_ROOT_CAUSES = "summarize_root_causes"
    EXPLAIN_DOMINANT_ROOT_CAUSE = "explain_dominant_root_cause"
    EXPLAIN_OPERATIONAL_FAILURES = "explain_operational_failures"
    SUMMARIZE_VERIFIED_FINDINGS = "summarize_verified_findings"
    EXPLAIN_WHY_TRADES_ARE_BLOCKED = "explain_why_trades_are_blocked"
    COMPARE_OPERATIONAL_PERIODS = "compare_operational_periods"
    COMPARE_BEFORE_AFTER_CLEANUP = "compare_before_after_cleanup"
    COMPARE_INVESTIGATION_PERIODS = "compare_investigation_periods"
    # Phase 56 — real-time conversational runtime
    WHAT_ARE_WE_DISCUSSING = "what_are_we_discussing"
    SUMMARIZE_CURRENT_CONVERSATION = "summarize_current_conversation"
    RESUME_PREVIOUS_TOPIC = "resume_previous_topic"
    SHOW_CONVERSATION_STATE = "show_conversation_state"
    START_CONTINUOUS_LISTENING = "start_continuous_listening"
    STOP_CONTINUOUS_LISTENING = "stop_continuous_listening"
    EXPLAIN_THIS_PROJECT = "explain_this_project"
    PREPARE_INVESTOR_SUMMARY = "prepare_investor_summary"
    EXPLAIN_ARCHITECTURE = "explain_architecture"
    GENERATE_PROJECT_ROADMAP = "generate_project_roadmap"
    SHOW_PROJECT_INTELLIGENCE = "show_project_intelligence"
    PROPOSE_ENGINEERING_PATCH = "propose_engineering_patch"
    SIMULATE_ENGINEERING_PATCH = "simulate_engineering_patch"
    VALIDATE_ENGINEERING_PATCH = "validate_engineering_patch"
    EXPLAIN_PATCH_RISKS = "explain_patch_risks"
    SHOW_PROACTIVE_SUGGESTIONS = "show_proactive_suggestions"
    SHOW_REALTIME_RUNTIME = "show_realtime_runtime"
    PHASE56_STATUS = "phase56_status"
    # Phase 57 — realtime streaming voice stack
    SHOW_VOICE_LATENCY = "show_voice_latency"
    SUMMARIZE_MY_DAY = "summarize_my_day"
    SUMMARIZE_MY_LAST_100_EMAILS = "summarize_my_last_100_emails"
    WHAT_NEEDS_MY_ATTENTION_TODAY = "what_needs_my_attention_today"
    FIND_CALENDAR_CONFLICTS = "find_calendar_conflicts"
    PHASE57_STATUS = "phase57_status"
    TEST_REALTIME_VOICE = "test_realtime_voice"
    TEST_INTERRUPT_SPEECH = "test_interrupt_speech"
    SHOW_REALTIME_PROVIDER_STATUS = "show_realtime_provider_status"
    BENCHMARK_REALTIME_PROVIDERS = "benchmark_realtime_providers"
    SHOW_REALTIME_LATENCY_BREAKDOWN = "show_realtime_latency_breakdown"
    TEST_WEBSOCKET_REALTIME_VOICE = "test_websocket_realtime_voice"
    BENCHMARK_REALTIME_STREAMING = "benchmark_realtime_streaming"
    SHOW_RUNTIME_CONFIG_SOURCES = "show_runtime_config_sources"
    SHOW_RUNTIME_CONFIG_MISMATCHES = "show_runtime_config_mismatches"
    SHOW_CAPABILITY_HEALTH = "show_capability_health"
    SHOW_CONVERSATION_RUNTIME = "show_conversation_runtime"
    SHOW_INTERRUPTION_METRICS = "show_interruption_metrics"
    SHOW_CONVERSATIONAL_MEMORY = "show_conversational_memory"
    BENCHMARK_FULL_DUPLEX_CONVERSATION = "benchmark_full_duplex_conversation"
    PHASE59_STATUS = "phase59_status"
    CANCEL_ACTIVE_SPEECH = "cancel_active_speech"
    # Phase 72 — bounded, read-only tool use (router-wired)
    PLAN_TOOL_TASK = "plan_tool_task"
    RUN_TOOL_TASK = "run_tool_task"
    SHOW_LAST_TOOL_RUN = "show_last_tool_run"
    UNKNOWN = "unknown"
    CLARIFY = "clarify"


class ActionStatus(str, Enum):
    """Outcome of an action execution."""

    SUCCESS = "success"
    FAILED = "failed"
    CLARIFICATION_NEEDED = "clarification_needed"
    CONFIRMATION_REQUIRED = "confirmation_required"
    NOT_IMPLEMENTED = "not_implemented"
    BLOCKED = "blocked"


class IntentClassification(BaseModel):
    """Structured output from LLM intent classifier (validated)."""

    intent: str
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    params: dict[str, Any] = Field(default_factory=dict)
    reason: str = ""
    classifier_source: str = "llm"
    valid: bool = True


class CommandRequest(BaseModel):
    """Incoming user command."""

    raw_text: str
    intent: Intent = Intent.UNKNOWN
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    params: dict[str, Any] = Field(default_factory=dict)
    language: str | None = None
    confirmed: bool = False
    confirmation_id: str | None = None
    classifier_source: str = "rules"


class CommandResult(BaseModel):
    """Structured result returned to the user and logs."""

    intent: Intent
    status: ActionStatus
    summary: str
    data: dict[str, Any] = Field(default_factory=dict)
    error: str | None = None
    requires_confirmation: bool = False
    confirmation_id: str | None = None
    next_suggestions: list[str] = Field(default_factory=list)

    @property
    def message(self) -> str:
        """Backward-compatible alias for summary."""
        return self.summary
