# Auto-extracted Phase 125 concepts
from __future__ import annotations
from typing import Any, Dict

LEGACY_CONCEPTS = {
    "ema": {
        "name": "EMA",
        "title": "Exponential Moving Average",
        "domain": "trading",
        "feature_type": "indicator",
        "aliases": (
            "ema",
            "exponential moving average",
            "exp moving average",
            "moving average ema",
            "trend filter ema",
        ),
        "meaning": (
            "A trend/price smoothing indicator calculated from a historical price series "
            "with exponential weighting on recent bars."
        ),
        "typical_locations": (
            "indicator calculation module",
            "strategy/signal generation",
            "config/parameters (period/span)",
            "backtest calculation path",
            "live/paper calculation path",
            "validation/tests",
        ),
        "path_keywords": (
            "indicator",
            "indicators",
            "ema",
            "moving",
            "average",
            "signal",
            "strategy",
            "ta",
            "technical",
        ),
        "required_inputs": ("price series (OHLCV)", "period/span configuration"),
        "required_outputs": ("EMA series aligned to bars", "signal-ready values after warmup"),
        "implementation_steps": (
            "Locate existing indicator/signal calculation path in the repo.",
            "Add EMA calculation (or extend the indicator registry) with configurable period/span.",
            "Integrate EMA into strategy entry/exit rules without changing unrelated logic.",
            "Ensure sufficient warmup bars before signals evaluate (period bars minimum).",
            "Ensure no lookahead: compute only from bars available at decision time.",
            "Wire the same calculation path (or provably equivalent logic) for backtest and live/paper.",
            "Add unit tests comparing output to a known reference (e.g. pandas ewm).",
        ),
        "implementation_risks": (
            "Lookahead bias (using future bars or incomplete bar close).",
            "Insufficient warmup bars (NaN or flat values suppress signals).",
            "Inconsistent backtest vs live/paper calculation path.",
            "Wrong price source (close vs open vs typical price).",
            "Period/span config drift between envs.",
            "NaN handling on initial bars.",
            "Recomputing from partial/forming bars in live mode.",
            "Performance on large universes (vectorize, avoid per-tick Python loops).",
        ),
        "common_bugs": (
            "EMA differs between backtest and paper because live uses forming bars.",
            "Warmup too short — signals fire before EMA is valid.",
            "Period mismatch between config and strategy code.",
        ),
        "verification": (
            "Compare EMA output against pandas/known fixture on a fixed price series.",
            "Test warmup: first valid index equals period-1 (or documented rule).",
            "Test no future bars used at signal timestamp.",
            "Test backtest/live calculation equivalence on identical bar stream.",
            "Test config period propagation from config → indicator → strategy.",
            "Run a small historical backtest before/after and diff signal timestamps.",
        ),
        "tests_to_run": (
            "Unit test EMA formula on fixture OHLCV.",
            "Integration test strategy signals with EMA filter enabled.",
            "Backtest vs paper parity test on same date range.",
        ),
        "related_concepts": ("rsi", "indicator_backtest_live", "backtest_live_divergence"),
    },
    "rsi": {
        "name": "RSI",
        "title": "Relative Strength Index",
        "domain": "trading",
        "feature_type": "indicator",
        "aliases": ("rsi", "relative strength index", "relative strength"),
        "meaning": "Momentum oscillator (0–100) from average gains vs losses over a lookback window.",
        "typical_locations": (
            "indicator module",
            "strategy/signal rules",
            "config (period, overbought/oversold thresholds)",
            "backtest and live paths",
        ),
        "path_keywords": ("rsi", "indicator", "signal", "strategy", "momentum", "oscillator"),
        "required_inputs": ("price series", "RSI period", "threshold levels"),
        "required_outputs": ("RSI series", "overbought/oversold signals"),
        "implementation_steps": (
            "Find indicator pipeline and strategy condition evaluation.",
            "Implement RSI with configurable period; document warmup length.",
            "Apply thresholds in strategy rules; avoid double-smoothing.",
            "Align backtest and live calculation; add fixture-based unit tests.",
        ),
        "implementation_risks": (
            "Warmup length off-by-one.",
            "Different smoothing (Wilder vs SMA) between backtest and live.",
            "Division by zero on flat markets.",
            "Lookahead on partial bars in live.",
        ),
        "common_bugs": (
            "RSI never reaches threshold because of wrong price field.",
            "Live RSI lags due to incomplete bar updates.",
        ),
        "verification": (
            "Compare to reference RSI on fixture data.",
            "Verify warmup bars before first signal.",
            "Backtest/live parity on same bars.",
        ),
        "tests_to_run": ("test_rsi_fixture", "strategy signal regression"),
        "related_concepts": ("ema", "indicator_backtest_live"),
    },
    "atr_stop_loss": {
        "name": "ATR stop loss",
        "title": "ATR-based stop loss",
        "domain": "trading",
        "feature_type": "risk",
        "aliases": (
            "atr stop",
            "atr stop loss",
            "atr trailing",
            "average true range stop",
            "atr based stop",
        ),
        "meaning": "Stop distance scaled by Average True Range volatility rather than fixed ticks.",
        "typical_locations": (
            "risk management",
            "order/execution",
            "position manager",
            "strategy exit rules",
        ),
        "path_keywords": ("atr", "stop", "risk", "trail", "exit", "position", "order"),
        "required_inputs": ("ATR period", "multiplier", "price series", "position state"),
        "required_outputs": ("stop price level", "trigger events"),
        "implementation_steps": (
            "Locate exit/stop evaluation and position lifecycle code.",
            "Compute ATR with correct true range formula and warmup.",
            "Set stop = entry ± multiplier × ATR; handle trailing updates.",
            "Ensure stop checks use intended bar field (close vs intrabar).",
            "Test stop triggers on historical replay.",
        ),
        "implementation_risks": (
            "Intrabar wick triggers vs close-only logic.",
            "Trailing stop ratchet direction wrong.",
            "ATR period mismatch across modes.",
            "Stop too tight after volatility spike.",
        ),
        "common_bugs": (
            "Stops fire on wicks in backtest but not live (or vice versa).",
            "ATR uses wrong timeframe.",
        ),
        "verification": (
            "Replay known bars and assert stop levels.",
            "Compare ATR to reference implementation.",
            "Paper trade one symbol with logged stop levels.",
        ),
        "tests_to_run": ("test_atr_formula", "test_stop_trigger_replay"),
        "related_concepts": ("ema", "backtest_live_divergence"),
    },
    "authentication": {
        "name": "Authentication",
        "title": "User authentication",
        "domain": "web_backend",
        "feature_type": "auth",
        "aliases": (
            "authentication",
            "auth",
            "login",
            "sign in",
            "signup",
            "jwt",
            "oauth",
            "session auth",
        ),
        "meaning": "Identity verification, sessions or tokens, and protected routes.",
        "typical_locations": (
            "user model",
            "auth routes/controllers",
            "session/token middleware",
            "password hashing",
            "permissions",
        ),
        "path_keywords": ("auth", "login", "session", "user", "identity", "jwt", "oauth", "password"),
        "required_inputs": ("credentials", "session store or JWT secret", "user persistence"),
        "required_outputs": ("authenticated session/token", "401/403 on protected routes"),
        "implementation_steps": (
            "Define user model and credential storage (hashed passwords).",
            "Add login/signup endpoints and session or JWT issuance.",
            "Protect routes with middleware/guards.",
            "Add permission checks on sensitive actions.",
            "Add tests for login, logout, and unauthorized access.",
        ),
        "implementation_risks": (
            "Session fixation",
            "Token leakage in logs",
            "Missing authorization on new endpoints",
            "Weak password policy",
        ),
        "common_bugs": ("Session expires unexpectedly", "Token not sent on API calls"),
        "verification": (
            "Test login/logout flows",
            "Test protected route without token returns 401",
            "Test role/permission boundaries",
        ),
        "tests_to_run": ("test_auth_login", "test_protected_route_401"),
        "related_concepts": ("rate_limiting", "stripe_billing"),
    },
    "stripe_billing": {
        "name": "Stripe billing",
        "title": "Stripe payments & subscriptions",
        "domain": "web_backend",
        "feature_type": "billing",
        "aliases": (
            "stripe",
            "billing",
            "subscription",
            "checkout",
            "payment",
            "stripe billing",
        ),
        "meaning": "Customer billing via Stripe Checkout, subscriptions, and webhooks.",
        "typical_locations": (
            "checkout/session creation",
            "webhook handler",
            "customer/subscription persistence",
            "billing portal",
        ),
        "path_keywords": ("stripe", "billing", "payment", "checkout", "subscription", "invoice", "webhook"),
        "required_inputs": ("Stripe API keys", "price IDs", "customer record", "webhook signing secret"),
        "required_outputs": ("checkout session", "subscription state", "idempotent webhook processing"),
        "implementation_steps": (
            "Model customer ↔ Stripe customer ID mapping.",
            "Create Checkout session or PaymentIntent flow.",
            "Implement webhook endpoint with signature verification.",
            "Update subscription state idempotently from events.",
            "Gate features by subscription status.",
        ),
        "implementation_risks": (
            "Webhook replay without idempotency",
            "Missing signature verification",
            "Race between checkout success and webhook",
            "Test vs live key mix-up",
        ),
        "common_bugs": ("Subscription active in Stripe but not in DB", "Double-charge on webhook retry"),
        "verification": (
            "Stripe CLI webhook replay in test mode",
            "Test checkout → webhook → entitlements",
            "Verify idempotency keys on events",
        ),
        "tests_to_run": ("test_webhook_signature", "test_subscription_state_sync"),
        "related_concepts": ("authentication"),
    },
    "rate_limiting": {
        "name": "Rate limiting",
        "title": "API rate limiting",
        "domain": "web_backend",
        "feature_type": "infra",
        "aliases": ("rate limit", "rate limiting", "throttle", "throttling", "429"),
        "meaning": "Cap request rates per client/IP/key to protect the service.",
        "typical_locations": ("middleware", "API gateway", "Redis counter", "reverse proxy config"),
        "path_keywords": ("rate", "limit", "throttle", "middleware", "redis", "api"),
        "required_inputs": ("limit policy", "identifier key", "window size"),
        "required_outputs": ("429 when exceeded", "headers indicating limit"),
        "implementation_steps": (
            "Choose limit scope (IP, user, API key).",
            "Implement counter (in-memory, Redis, or proxy).",
            "Apply middleware before handlers.",
            "Return consistent 429 + Retry-After.",
            "Load-test limits.",
        ),
        "implementation_risks": ("Shared NAT false positives", "Clock skew on windows", "Redis SPOF"),
        "common_bugs": ("Legitimate bursts blocked", "Limits not applied on all routes"),
        "verification": ("Burst test returns 429", "Limits reset after window"),
        "tests_to_run": ("test_rate_limit_middleware"),
        "related_concepts": ("authentication", "observability"),
    },
    "logging": {
        "name": "Structured logging",
        "title": "Logging / audit trail",
        "domain": "infra",
        "feature_type": "observability",
        "aliases": ("logging", "audit log", "structured log", "logger", "log aggregation"),
        "meaning": "Consistent structured logs for debugging, audit, and operations.",
        "typical_locations": ("logger setup", "middleware", "service modules", "log shipping"),
        "path_keywords": ("log", "logger", "audit", "trace", "telemetry"),
        "required_inputs": ("log level config", "correlation ID", "PII redaction rules"),
        "required_outputs": ("JSON/text logs", "request correlation"),
        "implementation_steps": (
            "Centralize logger configuration.",
            "Add correlation/request IDs in middleware.",
            "Redact secrets and PII.",
            "Define log levels per subsystem.",
        ),
        "implementation_risks": ("Log volume cost", "PII in logs", "Secret leakage"),
        "common_bugs": ("Missing context on errors", "Duplicate log lines"),
        "verification": ("Trigger error and verify trace ID in logs", "Scan sample logs for secrets"),
        "tests_to_run": ("test_logger_emits_structured_fields"),
        "related_concepts": ("observability", "retry_queue"),
    },
    "retry_queue": {
        "name": "Retry queue",
        "title": "Retry queue / async jobs",
        "domain": "infra",
        "feature_type": "queue",
        "aliases": ("retry queue", "dead letter", "celery", "task queue", "job queue", "worker queue"),
        "meaning": "Asynchronous work with retries, backoff, and dead-letter handling.",
        "typical_locations": ("worker", "broker", "task definitions", "scheduler"),
        "path_keywords": ("queue", "worker", "celery", "task", "job", "broker", "retry", "rabbit", "redis"),
        "required_inputs": ("broker URL", "retry policy", "idempotent handlers"),
        "required_outputs": ("enqueued jobs", "DLQ for failures"),
        "implementation_steps": (
            "Define task handlers as idempotent.",
            "Configure broker and retry/backoff.",
            "Add dead-letter or failed-job storage.",
            "Monitor queue depth and lag.",
        ),
        "implementation_risks": ("Non-idempotent retries duplicate side effects", "Poison messages"),
        "common_bugs": ("Tasks stuck in queue", "Retry storm overloads downstream"),
        "verification": ("Fail task twice — single side effect", "DLQ receives poison message"),
        "tests_to_run": ("test_task_retry_idempotent"),
        "related_concepts": ("logging", "observability"),
    },
    "observability": {
        "name": "Observability",
        "title": "Metrics, traces, and health checks",
        "domain": "infra",
        "feature_type": "observability",
        "aliases": ("observability", "metrics", "prometheus", "tracing", "health check", "monitoring"),
        "meaning": "Operational visibility: metrics, distributed traces, and health endpoints.",
        "typical_locations": ("metrics middleware", "trace instrumentation", "/health routes"),
        "path_keywords": ("metric", "prometheus", "trace", "health", "monitor", "otel", "statsd"),
        "required_inputs": ("metric names/labels", "trace exporter", "SLIs"),
        "required_outputs": ("scraped metrics", "trace spans", "200/503 health"),
        "implementation_steps": (
            "Add health/readiness endpoints.",
            "Instrument key paths with metrics.",
            "Add trace context propagation.",
            "Dashboard critical SLIs.",
        ),
        "implementation_risks": ("Cardinality explosion", "PII in traces", "Health check too shallow"),
        "common_bugs": ("Metrics missing on error paths", "Health green while dependencies down"),
        "verification": ("Scrape metrics in staging", "Break dependency — readiness fails"),
        "tests_to_run": ("test_health_endpoint", "test_metrics_increment"),
        "related_concepts": ("logging", "rate_limiting"),
    },
    "backtest_live_divergence": {
        "name": "Backtest vs live/paper divergence",
        "title": "Backtest/live behavioral mismatch",
        "domain": "trading",
        "feature_type": "symptom",
        "aliases": (
            "backtest better than paper",
            "backtest better than live",
            "better than paper trading",
            "better than paper",
            "better than live",
            "much better than paper",
            "much better than live",
            "paper worse than backtest",
            "live worse than backtest",
            "simulation better than live",
        ),
        "meaning": "Performance or behavior differs between simulation and live/paper execution.",
        "typical_locations": (
            "backtest engine",
            "paper/live execution engine",
            "data feed",
            "fill/slippage model",
            "signal timing",
        ),
        "path_keywords": ("backtest", "paper", "live", "sim", "execution", "broker", "fill", "slippage"),
        "required_inputs": ("comparable bar stream", "execution logs from both modes"),
        "required_outputs": ("identified divergence point"),
        "implementation_steps": (),  # investigate-only
        "implementation_risks": (),
        "common_bugs": (
            "Fill price mismatch (ideal next-bar vs latest quote).",
            "Signal timing mismatch (closed bar vs forming bar).",
            "Slippage/gap modeling only in one mode.",
            "Ranking/capacity constraints ignored in backtest.",
            "Stale price in live.",
            "Rejected orders not modeled in backtest.",
            "Session/timezone mismatch.",
            "Fees/commission applied inconsistently.",
        ),
        "verification": (
            "Log signal timestamp and fill price for one trade in both modes.",
            "Diff bar stream and indicator values at signal time.",
            "Compare fee/slippage assumptions side by side.",
        ),
        "tests_to_run": ("parity test on fixed bar stream"),
        "related_concepts": ("ema", "indicator_backtest_live"),
        "investigate_only": True,
    },
    "indicator_backtest_live": {
        "name": "Indicator backtest/live mismatch",
        "title": "Indicator works in backtest but not live/paper",
        "domain": "trading",
        "feature_type": "symptom",
        "aliases": (
            "works in backtest but not live",
            "works in backtest but not paper",
            "backtest but not paper",
            "backtest but not live",
            "indicator works in backtest",
            "ema works in backtest",
            "signal works in backtest",
        ),
        "meaning": "Indicator or signal logic passes backtest but fails or stays flat in live/paper.",
        "typical_locations": (
            "indicator calculation",
            "data feed / bar builder",
            "strategy signal evaluation",
            "config",
        ),
        "path_keywords": ("indicator", "signal", "backtest", "paper", "live", "ema", "rsi", "bar", "feed"),
        "required_inputs": ("indicator values at signal time in both modes"),
        "required_outputs": ("root cause of value/timing mismatch"),
        "implementation_steps": (),
        "implementation_risks": (),
        "common_bugs": (
            "Indicator calculation mismatch between paths.",
            "Partial/forming candle used in live but closed bar in backtest.",
            "Live price source mismatch (bid/ask vs last vs close).",
            "Warmup data length shorter in live.",
            "Config period mismatch.",
            "NaN handling suppresses live signals.",
        ),
        "verification": (
            "Dump indicator series for same symbol/date in both modes.",
            "Verify bar timestamps align at signal evaluation.",
            "Check warmup bar count before first live signal.",
        ),
        "tests_to_run": ("indicator parity fixture test"),
        "related_concepts": ("ema", "rsi", "backtest_live_divergence"),
        "investigate_only": True,
    },
}


