"""Phase 128 — 150 curated concepts (source-backed + curated-deep)."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from .concept_builder import build_concept

# Shared checklist fragments by domain
_TEMPLATES: Dict[str, Dict[str, List[str]]] = {
    "security": {
        "risks": ["Broken trust boundary", "Credential leakage"],
        "security_risks": ["Token/session theft", "Privilege escalation", "Replay attacks"],
        "failure_modes": ["Auth bypass on misconfigured middleware", "Stale permissions after role change"],
        "verification": ["Threat-model critical paths", "Validate negative tests for unauthorized access"],
        "testing": ["AuthZ matrix tests", "Session fixation/replay tests"],
        "implementation_strategies": ["Fail closed on validation errors", "Centralize auth middleware"],
    },
    "backend": {
        "risks": ["Contract drift between clients and server", "Unhandled edge cases on partial failure"],
        "performance_risks": ["N+1 queries", "Unbounded payload size", "Hot-spot endpoints"],
        "failure_modes": ["500s under load without backpressure", "Inconsistent error shapes for clients"],
        "verification": ["OpenAPI/contract tests", "Load test critical endpoints"],
        "testing": ["Integration tests with realistic payloads", "Contract tests for error codes"],
        "implementation_strategies": ["Validate at boundary", "Idempotent writes where applicable"],
    },
    "databases": {
        "risks": ["Data corruption", "Lock contention"],
        "performance_risks": ["Missing indexes", "Long-running transactions", "Connection pool exhaustion"],
        "failure_modes": ["Migration lock on large tables", "Deadlocks under concurrent updates"],
        "verification": ["Explain plans for hot queries", "Migration rollback drill"],
        "testing": ["Migration up/down tests", "Concurrency tests on hot rows"],
        "implementation_strategies": ["Migrations additive-first", "Explicit transaction boundaries"],
    },
    "distributed_systems": {
        "risks": ["Cascading failures", "Split-brain"],
        "performance_risks": ["Retry storms", "Queue backlog"],
        "failure_modes": ["Duplicate side effects on retry", "Partial failure leaves inconsistent state"],
        "verification": ["Chaos/fault injection on dependencies", "Idempotency key audit"],
        "testing": ["Failure injection tests", "Idempotent handler tests"],
        "implementation_strategies": ["Timeouts + bulkheads", "Outbox/inbox for cross-service consistency"],
    },
    "observability": {
        "risks": ["Blind spots during incidents", "PII in logs"],
        "performance_risks": ["High-cardinality metrics", "Log volume cost"],
        "failure_modes": ["Alerts fire without actionable context", "Missing correlation across services"],
        "verification": ["Trace a single request end-to-end", "Redact secrets in log samples"],
        "testing": ["Assert required fields on log lines", "Synthetic probe alerts"],
        "implementation_strategies": ["Correlation IDs on all requests", "RED metrics for SLIs"],
    },
    "cloud": {
        "risks": ["Misconfigured IAM", "Public exposure"],
        "security_risks": ["Over-privileged roles", "Secrets in environment variables"],
        "failure_modes": ["Deploy succeeds but health checks fail", "Autoscaling lag during spike"],
        "verification": ["Least-privilege IAM review", "Disaster recovery drill"],
        "testing": ["IaC plan/apply in CI", "Smoke test after deploy"],
        "implementation_strategies": ["Infrastructure as code", "Separate env accounts"],
    },
    "ci_cd": {
        "risks": ["Broken pipeline blocks releases", "Flaky gates"],
        "failure_modes": ["Deploy without migration order", "Secrets leaked in CI logs"],
        "verification": ["Pipeline reproduces on clean runner", "Artifact signing verified"],
        "testing": ["CI runs on every PR", "Canary/rollback playbook tested"],
        "implementation_strategies": ["Build once, promote artifacts", "Required checks before merge"],
    },
    "trading": {
        "risks": ["Lookahead bias", "Backtest/live divergence"],
        "performance_risks": ["Python loops on large universes", "Memory growth in streaming"],
        "failure_modes": ["Signals on NaN indicators", "Fill model mismatch vs live"],
        "verification": ["Parity test on fixed bar stream", "Compare to reference implementation"],
        "testing": ["Unit tests on indicator fixtures", "Paper/backtest reconciliation"],
        "implementation_strategies": ["Single source of truth for bar timestamps", "Shared calculator for sim/live"],
    },
    "frontend": {
        "risks": ["State desync", "XSS via rendered HTML"],
        "security_risks": ["XSS", "CSRF on state-changing actions"],
        "performance_risks": ["Re-render storms", "Large bundle size"],
        "failure_modes": ["UI shows stale data after mutation", "Hydration mismatch"],
        "verification": ["Accessibility audit", "Cross-browser smoke"],
        "testing": ["Component tests", "E2E critical flows"],
        "implementation_strategies": ["Unidirectional data flow", "Explicit loading/error states"],
    },
    "testing": {
        "risks": ["False confidence from shallow tests"],
        "failure_modes": ["Flaky tests ignored", "Tests coupled to implementation details"],
        "verification": ["Coverage on critical paths not lines only", "Mutation testing sample"],
        "testing": ["CI parallelization", "Test data fixtures versioned"],
        "implementation_strategies": ["Test pyramid balance", "Deterministic test clocks"],
    },
    "machine_learning": {
        "risks": ["Training/serving skew", "Data leakage"],
        "performance_risks": ["GPU memory spikes", "Batch latency SLO miss"],
        "failure_modes": ["Model drift undetected", "Non-reproducible training"],
        "verification": ["Offline metrics on holdout", "Shadow mode in production"],
        "testing": ["Golden-file inference outputs", "Pipeline integration tests"],
        "implementation_strategies": ["Version datasets and models", "Feature store contracts"],
    },
    "software_architecture": {
        "risks": ["Accidental complexity", "Unclear module boundaries"],
        "failure_modes": ["Circular dependencies", "God modules"],
        "verification": ["Architecture fitness functions", "Dependency rule tests"],
        "testing": ["ArchUnit-style constraints", "Contract tests between modules"],
        "implementation_strategies": ["Explicit boundaries", "Document architectural decisions"],
    },
    "apis": {
        "risks": ["Breaking clients on change"],
        "performance_risks": ["Chatty APIs", "Overserialized payloads"],
        "failure_modes": ["Undocumented error codes", "Version skew"],
        "verification": ["Consumer-driven contracts", "Backward compatibility checklist"],
        "testing": ["Contract tests", "Load tests on gateway"],
        "implementation_strategies": ["Versioning strategy", "Pagination and limits"],
    },
}


def _tpl(domain: str) -> Dict[str, List[str]]:
    if domain in _TEMPLATES:
        return _TEMPLATES[domain]
    for key in _TEMPLATES:
        if domain.startswith(key.split("_")[0]):
            return _TEMPLATES[key]
    return _TEMPLATES["backend"]


def _entry(
    cid: str,
    name: str,
    domain: str,
    category: str,
    quality: str,
    aliases: List[str],
    description: str,
    when_to_use: str,
    references: List[str],
    *,
    related: Optional[List[str]] = None,
    path_keywords: Optional[List[str]] = None,
    requirements: Optional[List[str]] = None,
    implementation_strategies: Optional[List[str]] = None,
    risks: Optional[List[str]] = None,
    security_risks: Optional[List[str]] = None,
    performance_risks: Optional[List[str]] = None,
    failure_modes: Optional[List[str]] = None,
    verification: Optional[List[str]] = None,
    testing: Optional[List[str]] = None,
    investigate_only: bool = False,
) -> Dict[str, Any]:
    t = _tpl(domain)
    return build_concept(
        concept_id=cid,
        name=name,
        domain=domain,
        category=category,
        concept_quality_score=quality,
        aliases=aliases,
        description=description,
        when_to_use=when_to_use,
        requirements=requirements or [f"Clear ownership of {name} in the architecture"],
        implementation_strategies=implementation_strategies or t.get("implementation_strategies", []),
        common_implementations=implementation_strategies or t.get("implementation_strategies", []),
        risks=(risks or []) + t.get("risks", []),
        security_risks=security_risks or t.get("security_risks", []),
        performance_risks=performance_risks or t.get("performance_risks", []),
        failure_modes=(failure_modes or []) + t.get("failure_modes", []),
        verification=(verification or []) + t.get("verification", []),
        testing=(testing or []) + t.get("testing", []),
        related_concepts=related or [],
        references=references,
        path_keywords=path_keywords,
        investigate_only=investigate_only,
    )


def _source_backed() -> List[Dict[str, Any]]:
    """55 source-backed concepts (RFCs, official docs, vendor docs)."""
    return [
        _entry(
            "jwt", "JWT", "security", "authentication", "source_backed",
            ["jwt", "json web token", "bearer token"],
            "Compact signed claims (RFC 7519) for stateless auth: header.payload.signature.",
            "Use for machine-to-machine or SPA/mobile APIs when sessions are undesirable; pair with refresh tokens for UX.",
            ["RFC 7519 - JSON Web Token (JWT)", "RFC 8725 - JWT Best Current Practices"],
            related=["oauth2", "authentication", "rbac"],
            path_keywords=["auth", "jwt", "token", "middleware", "bearer"],
            requirements=["Signing keys or JWKS", "Short-lived access tokens", "Algorithm allow-list"],
            security_risks=["Algorithm confusion (none/HS vs RS)", "Token theft via XSS", "Replay without rotation"],
            verification=["Reject tampered payloads", "Validate exp/nbf/iss/aud", "Test refresh rotation"],
            testing=["Boundary tests on claims", "Security tests for alg-none attacks"],
        ),
        _entry(
            "oauth2", "OAuth 2.0", "security", "authentication", "source_backed",
            ["oauth", "oauth2", "authorization code", "delegated auth"],
            "Industry-standard delegated authorization (RFC 6749) — obtain access tokens without sharing passwords.",
            "When third-party apps need limited access to user resources; prefer Authorization Code + PKCE for public clients.",
            ["RFC 6749 - OAuth 2.0 Authorization Framework", "RFC 7636 - PKCE"],
            related=["jwt", "authentication"],
            security_risks=["Redirect URI open redirect", "Leaked client secrets", "Scope escalation"],
            verification=["Validate state parameter", "Exchange code only once", "Rotate refresh tokens"],
        ),
        _entry(
            "ema", "EMA", "trading", "indicator", "source_backed",
            ["ema", "exponential moving average", "moving average ema"],
            "Exponentially weighted moving average; alpha=2/(N+1) for span N; needs warmup of N bars.",
            "Trend filtering and signal gating on price series; require identical bar semantics in backtest and live.",
            ["https://pandas.pydata.org/docs/reference/api/pandas.Series.ewm.html"],
            related=["rsi", "indicator_backtest_live", "backtest_live_divergence"],
            path_keywords=["indicator", "ema", "signal", "strategy", "backtest"],
            performance_risks=["O(n) per recompute on large universes if not vectorized"],
            verification=["Fixture compare vs reference", "Warmup bar count", "No lookahead at signal time"],
        ),
        _entry(
            "postgresql", "PostgreSQL", "databases", "sql", "source_backed",
            ["postgresql", "postgres", "psql"],
            "ACID relational database with rich SQL, indexes, and extensions.",
            "Default choice for transactional apps needing strong consistency and complex queries.",
            ["https://www.postgresql.org/docs/current/"],
            path_keywords=["postgres", "sql", "database", "migration", "orm"],
            verification=["EXPLAIN ANALYZE on hot queries", "Backup/restore drill"],
        ),
        _entry(
            "stripe_billing", "Stripe Billing", "backend", "billing", "source_backed",
            ["stripe", "stripe billing", "subscriptions", "checkout"],
            "Stripe Checkout + Billing for payments and subscriptions with webhook-driven state.",
            "When you need PCI-scoped card handling and subscription lifecycle without building payments from scratch.",
            ["https://stripe.com/docs/billing", "https://stripe.com/docs/webhooks"],
            related=["webhook_receiver", "authentication"],
            security_risks=["Webhook signature bypass", "Live/test key mix-up"],
            verification=["Stripe CLI webhook replay", "Idempotent event handling"],
        ),
        _entry(
            "rate_limiting", "Rate Limiting", "backend", "middleware", "source_backed",
            ["rate limit", "rate limiting", "throttle", "429"],
            "Enforce per-client request quotas using token bucket or sliding window counters.",
            "Protect public APIs and auth endpoints from abuse; return 429 + Retry-After.",
            ["https://datatracker.ietf.org/doc/html/rfc6585#section-4"],
            related=["api_gateway", "redis_cache"],
            performance_risks=["Redis SPOF for global counters", "Thundering herd after throttle lifts"],
        ),
        _entry(
            "database_migration", "Database Migration", "databases", "migration", "source_backed",
            ["database migration", "schema migration", "alembic", "flyway"],
            "Versioned, ordered schema changes applied via migration tool.",
            "Every production schema change; prefer additive migrations before code deploy.",
            ["https://www.postgresql.org/docs/current/ddl-alter.html"],
            related=["postgresql", "transaction_isolation"],
            failure_modes=["Lock timeout on large table rewrite", "Irreversible drop without backup"],
        ),
        _entry(
            "rest_api", "REST API", "apis", "rest", "source_backed",
            ["rest", "restful", "http api"],
            "Resource-oriented HTTP API using verbs, status codes, and representations.",
            "Default for public HTTP integrations; document with OpenAPI.",
            ["https://www.iana.org/assignments/http-methods", "https://openapi.org/specification"],
            related=["graphql_api", "grpc_api", "api_versioning"],
        ),
        _entry(
            "graphql_api", "GraphQL", "apis", "graphql", "source_backed",
            ["graphql", "graph ql"],
            "Schema-typed query language over a single HTTP endpoint.",
            "When clients need flexible field selection; watch N+1 and complexity limits.",
            ["https://spec.graphql.org/"],
            performance_risks=["Deep queries", "Resolver N+1"],
        ),
        _entry(
            "grpc_api", "gRPC", "apis", "grpc", "source_backed",
            ["grpc", "protobuf rpc"],
            "Binary RPC over HTTP/2 with Protocol Buffers contracts.",
            "Service-to-service low-latency RPC inside trusted networks.",
            ["https://grpc.io/docs/what-is-grpc/"],
        ),
        _entry(
            "circuit_breaker", "Circuit Breaker", "distributed_systems", "resilience", "source_backed",
            ["circuit breaker", "breaker pattern"],
            "Stop calling failing dependency after threshold; half-open probe for recovery.",
            "Wrap external HTTP/DB calls with timeouts and breaker to prevent retry storms.",
            ["https://learn.microsoft.com/azure/architecture/patterns/circuit-breaker"],
            related=["retry_backoff"],
        ),
        _entry(
            "retry_backoff", "Retry with Backoff", "distributed_systems", "resilience", "source_backed",
            ["retry", "exponential backoff", "jitter"],
            "Retry transient failures with exponential backoff and jitter.",
            "Idempotent operations only; cap max attempts.",
            ["https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/"],
            related=["circuit_breaker", "idempotency_key"],
        ),
        _entry(
            "structured_logging", "Structured Logging", "observability", "logging", "source_backed",
            ["structured log", "json logging"],
            "Machine-parseable logs (JSON) with stable field names.",
            "Always in production services; include trace/request IDs.",
            ["https://opentelemetry.io/docs/specs/otel/logs/"],
            related=["distributed_tracing"],
        ),
        _entry(
            "distributed_tracing", "Distributed Tracing", "observability", "tracing", "source_backed",
            ["distributed tracing", "opentelemetry", "trace", "span"],
            "Correlate work across services via trace/span IDs (OpenTelemetry).",
            "Any multi-service request path; required for debugging latency.",
            ["https://opentelemetry.io/docs/concepts/signals/traces/"],
        ),
        _entry(
            "authentication", "Authentication", "authentication", "auth", "source_backed",
            ["authentication", "auth", "login", "sign in"],
            "Verify identity (who you are) before authorization.",
            "Every user-facing app with protected resources.",
            ["https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html"],
            related=["oauth2", "jwt", "rbac"],
        ),
        _entry(
            "webhook_receiver", "Webhook Receiver", "backend", "integration", "source_backed",
            ["webhook", "callback endpoint", "stripe webhook"],
            "HTTP endpoint that verifies provider signatures and processes events idempotently.",
            "Stripe/GitHub/Slack integrations; never trust payload without signature.",
            ["https://stripe.com/docs/webhooks/signatures"],
            related=["stripe_billing", "idempotency_key"],
        ),
        _entry(
            "idempotency_key", "Idempotency Key", "backend", "reliability", "source_backed",
            ["idempotency", "idempotent", "idempotency-key"],
            "Client-supplied key so retries do not duplicate side effects.",
            "POST/PUT payment or create operations exposed to retries.",
            ["https://stripe.com/docs/api/idempotent_requests"],
        ),
        _entry(
            "redis_cache", "Redis", "databases", "cache", "source_backed",
            ["redis", "cache", "in-memory"],
            "In-memory data store for cache, rate limits, pub/sub, and sessions.",
            "Low-latency ephemeral state with TTL; not primary source of truth.",
            ["https://redis.io/docs/"],
            performance_risks=["Memory pressure", "Hot keys"],
        ),
        _entry(
            "kubernetes", "Kubernetes", "cloud", "orchestration", "source_backed",
            ["kubernetes", "k8s", "kubectl", "deployment"],
            "Container orchestration: deploy, scale, and heal workloads.",
            "Production container workloads at scale.",
            ["https://kubernetes.io/docs/home/"],
            related=["docker", "health_check"],
        ),
        _entry(
            "docker", "Docker", "cloud", "container", "source_backed",
            ["docker", "container image", "dockerfile"],
            "Package apps with dependencies into immutable images.",
            "Standard unit for deployable artifacts in CI/CD.",
            ["https://docs.docker.com/get-started/"],
        ),
        _entry(
            "feature_flags", "Feature Flags", "backend", "release", "source_backed",
            ["feature flag", "feature toggle", "launchdarkly"],
            "Runtime configuration to enable features per user/tenant without redeploy.",
            "Gradual rollouts and kill switches for risky changes.",
            ["https://martinfowler.com/articles/feature-toggles.html"],
            verification=["Flag off path tested", "Default-safe values on failure"],
        ),
        _entry(
            "secrets_management", "Secrets Management", "security", "secrets", "source_backed",
            ["secrets", "vault", "api keys", "secrets manager"],
            "Store and rotate credentials outside source control.",
            "All API keys, DB passwords, signing keys in prod.",
            ["https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html"],
            security_risks=["Secrets in git history", "Over-broad IAM to secret store"],
        ),
        _entry(
            "tls_https", "TLS / HTTPS", "security", "transport", "source_backed",
            ["tls", "https", "ssl", "mtls"],
            "Encrypt data in transit; TLS 1.2+; consider mTLS service-to-service.",
            "All external endpoints; enforce HSTS where applicable.",
            ["RFC 8446 - TLS 1.3"],
        ),
        _entry(
            "sql_injection", "SQL Injection", "security", "vulnerability", "source_backed",
            ["sql injection", "sqli"],
            "Untrusted input alters SQL execution.",
            "Prevent via parameterized queries/ORM; never concatenate SQL.",
            ["https://owasp.org/www-community/attacks/SQL_Injection"],
            security_risks=["ORM raw query misuse", "Dynamic ORDER BY injection"],
        ),
        _entry(
            "rbac", "RBAC", "authorization", "authorization", "source_backed",
            ["rbac", "roles", "permissions"],
            "Grant permissions via roles assigned to principals.",
            "Admin apps and multi-tenant SaaS authorization models.",
            ["https://csrc.nist.gov/projects/role-based-access-control"],
            related=["authentication"],
        ),
        _entry(
            "event_sourcing", "Event Sourcing", "distributed_systems", "pattern", "source_backed",
            ["event sourcing", "event store"],
            "Persist state changes as append-only events; projections build read models.",
            "Audit-heavy domains; accept operational complexity.",
            ["https://martinfowler.com/eaaDev/EventSourcing.html"],
            related=["cqrs"],
        ),
        _entry(
            "cqrs", "CQRS", "distributed_systems", "pattern", "source_backed",
            ["cqrs", "command query separation"],
            "Separate write (commands) and read (queries) models.",
            "High read/write asymmetry; pairs with event sourcing often.",
            ["https://martinfowler.com/bliki/CQRS.html"],
        ),
        _entry(
            "saga_pattern", "Saga Pattern", "distributed_systems", "pattern", "source_backed",
            ["saga", "distributed transaction"],
            "Multi-step business transaction with compensating actions on failure.",
            "Cross-service workflows without 2PC.",
            ["https://microservices.io/patterns/data/saga.html"],
        ),
        _entry(
            "backtest_live_divergence", "Backtest vs Live Divergence", "trading", "symptom", "source_backed",
            ["backtest better than paper", "backtest better than live", "paper worse than backtest"],
            "Performance or behavior differs between simulation and live/paper.",
            "Investigate when sim results cannot be reproduced live.",
            ["atlas://trading/backtest-live-parity"],
            investigate_only=True,
            related=["ema", "indicator_backtest_live"],
        ),
        _entry(
            "indicator_backtest_live", "Indicator Backtest/Live Mismatch", "trading", "symptom", "source_backed",
            ["works in backtest but not live", "indicator backtest live"],
            "Indicator/signal differs between backtest and live paths.",
            "When signals fire in sim but not production.",
            ["atlas://trading/indicator-parity"],
            investigate_only=True,
        ),
        _entry(
            "openai_api", "OpenAI API Integration", "ai_infrastructure", "llm", "source_backed",
            ["openai api", "chat completions", "gpt api"],
            "HTTP API for LLM completions, embeddings, and tools.",
            "When product requires OpenAI models; handle keys, rate limits, and timeouts.",
            ["https://platform.openai.com/docs/api-reference"],
            security_risks=["API key leakage", "Prompt injection via user content"],
        ),
        _entry(
            "rag_pipeline", "RAG Pipeline", "ai_infrastructure", "rag", "source_backed",
            ["rag", "retrieval augmented generation"],
            "Retrieve relevant documents then prompt LLM with grounded context.",
            "Q&A over private docs; reduces hallucination vs raw LLM.",
            ["https://python.langchain.com/docs/concepts/rag/"],
            performance_risks=["Embedding index size", "Retrieval latency"],
        ),
        _entry(
            "ci_cd_pipeline", "CI/CD Pipeline", "ci_cd", "pipeline", "source_backed",
            ["ci/cd", "continuous integration", "github actions", "pipeline"],
            "Automated build, test, and deploy on each change.",
            "All teams shipping to production.",
            ["https://martinfowler.com/articles/continuousIntegration.html"],
            related=["feature_flags", "database_migration"],
        ),
        _entry(
            "health_check", "Health Check", "backend", "operations", "source_backed",
            ["health check", "readiness", "liveness"],
            "Liveness (process up) vs readiness (can serve traffic) endpoints.",
            "Kubernetes/orchestrator probes; load balancer checks.",
            ["https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/"],
        ),
        _entry(
            "database_index", "Database Index", "databases", "index", "source_backed",
            ["database index", "btree", "index"],
            "Data structure accelerating lookups at cost of write overhead.",
            "Slow SELECT/WHERE/ORDER BY on large tables.",
            ["https://www.postgresql.org/docs/current/indexes.html"],
            performance_risks=["Wrong index type", "Index bloat"],
        ),
        _entry(
            "transaction_isolation", "Transaction Isolation", "databases", "transaction", "source_backed",
            ["isolation level", "serializable", "read committed"],
            "Controls visibility of concurrent transactions (ANSI levels).",
            "When debugging anomalies (phantom reads, write skew).",
            ["https://www.postgresql.org/docs/current/transaction-iso.html"],
        ),
        _entry(
            "connection_pooling", "Connection Pooling", "databases", "pool", "source_backed",
            ["connection pool", "pgbouncer"],
            "Reuse DB connections to avoid handshake overhead.",
            "Every app server talking to PostgreSQL/MySQL.",
            ["https://www.postgresql.org/docs/current/runtime-config-connection.html"],
        ),
        _entry(
            "api_versioning", "API Versioning", "apis", "versioning", "source_backed",
            ["api version", "versioned api", "v1 api"],
            "Explicit contract versions for backward-compatible evolution.",
            "Public APIs with external clients.",
            ["https://martinfowler.com/articles/versioningRESTApis.html"],
        ),
        _entry(
            "csrf_protection", "CSRF Protection", "security", "web", "source_backed",
            ["csrf", "cross site request forgery"],
            "Prevent browsers from executing state-changing requests without intent.",
            "Cookie-session web apps with form POST.",
            ["https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html"],
        ),
        _entry(
            "xss", "Cross-Site Scripting", "security", "vulnerability", "source_backed",
            ["xss", "cross site scripting"],
            "Inject scripts executing in victim browser context.",
            "Any app rendering user HTML/JS.",
            ["https://owasp.org/www-community/attacks/xss/"],
        ),
        _entry(
            "metrics_histogram", "Metrics Histogram", "observability", "metrics", "source_backed",
            ["histogram", "percentile latency", "prometheus histogram"],
            "Track distribution of values (e.g. latency) for SLOs.",
            "Latency/error SLIs in production.",
            ["https://prometheus.io/docs/practices/histograms/"],
        ),
        _entry(
            "retry_queue", "Retry Queue", "messaging", "queue", "source_backed",
            ["retry queue", "dead letter", "dlq"],
            "Async retries with backoff and dead-letter for poison messages.",
            "Background jobs with transient failures.",
            ["https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/"],
            related=["retry_backoff"],
        ),
        _entry(
            "observability", "Observability", "observability", "platform", "source_backed",
            ["observability", "monitoring", "o11y"],
            "Logs, metrics, and traces sufficient to debug unknown failures.",
            "Production services with SLOs.",
            ["https://opentelemetry.io/docs/concepts/observability-primer/"],
        ),
        _entry(
            "helm_chart", "Helm Chart", "cloud", "deploy", "source_backed",
            ["helm", "helm chart", "kubernetes package"],
            "Package Kubernetes manifests as versioned charts.",
            "Deploying apps to Kubernetes with templated config.",
            ["https://helm.sh/docs/"],
        ),
        _entry(
            "terraform_iac", "Terraform IaC", "cloud", "iac", "source_backed",
            ["terraform", "infrastructure as code", "iac"],
            "Declarative infrastructure provisioning with state.",
            "Cloud resource lifecycle in teams.",
            ["https://developer.hashicorp.com/terraform/docs"],
        ),
        _entry(
            "aws_lambda", "AWS Lambda", "cloud", "serverless", "source_backed",
            ["aws lambda", "serverless function"],
            "Event-driven functions without managing servers.",
            "Spiky workloads and glue automation.",
            ["https://docs.aws.amazon.com/lambda/"],
        ),
        _entry(
            "react_state", "React State Management", "frontend", "state", "source_backed",
            ["react state", "usestate", "redux"],
            "Manage UI state with hooks/context or external stores.",
            "Interactive React apps beyond trivial forms.",
            ["https://react.dev/learn/managing-state"],
        ),
        _entry(
            "unit_testing", "Unit Testing", "testing", "unit", "source_backed",
            ["unit test", "unit testing"],
            "Test isolated units with mocks for dependencies.",
            "Fast feedback on pure logic and components.",
            ["https://martinfowler.com/bliki/UnitTest.html"],
        ),
        _entry(
            "integration_testing", "Integration Testing", "testing", "integration", "source_backed",
            ["integration test", "integration testing"],
            "Test collaboration of modules with real DB/broker where needed.",
            "API and repository layers before E2E.",
            ["https://martinfowler.com/bliki/IntegrationTest.html"],
        ),
        _entry(
            "microservices", "Microservices", "software_architecture", "style", "source_backed",
            ["microservices", "microservice architecture"],
            "Independently deployable services around business capabilities.",
            "Large teams needing independent release cadence; accept distributed ops cost.",
            ["https://martinfowler.com/articles/microservices.html"],
        ),
        _entry(
            "api_gateway", "API Gateway", "software_architecture", "gateway", "source_backed",
            ["api gateway", "edge gateway"],
            "Single entry for routing, auth, rate limits, and TLS termination.",
            "Multiple backend services behind one public host.",
            ["https://learn.microsoft.com/azure/architecture/microservices/architectural-patterns/api-gateway"],
        ),
        _entry(
            "domain_driven_design", "Domain-Driven Design", "software_architecture", "ddd", "source_backed",
            ["ddd", "domain driven design", "bounded context"],
            "Model software around domain language and bounded contexts.",
            "Complex business domains with evolving rules.",
            ["https://www.domainlanguage.com/ddd/"],
        ),
    ]


def _curated_deep() -> List[Dict[str, Any]]:
    """95 curated-deep concepts (architect-grade, not template-only)."""
    specs = [
        ("rsi", "RSI", "trading", "indicator", ["rsi", "relative strength index"],
         "Momentum oscillator 0-100 from average gains/losses over N periods.",
         "Overbought/oversold filters; align Wilder smoothing with reference."),
        ("atr_stop_loss", "ATR Stop Loss", "trading", "risk", ["atr stop", "atr stop loss"],
         "Stop distance scaled by Average True Range volatility.",
         "Volatility-adjusted exits; define intrabar vs close trigger rules."),
        ("middleware_pipeline", "Middleware Pipeline", "backend", "middleware", ["middleware", "request pipeline"],
         "Composable request/response chain for auth, logging, limits.",
         "Cross-cutting concerns before route handlers."),
        ("pagination_cursor", "Cursor Pagination", "backend", "api", ["cursor pagination", "keyset"],
         "Stable paging with opaque cursors instead of OFFSET.",
         "Large tables where OFFSET is too slow."),
        ("outbox_pattern", "Outbox Pattern", "distributed_systems", "pattern", ["outbox", "transactional outbox"],
         "Write events to outbox table in same TX as domain write.",
         "Reliable publish after DB commit."),
        ("inbox_pattern", "Inbox Pattern", "distributed_systems", "pattern", ["inbox", "idempotent consumer"],
         "Dedupe incoming events via inbox table.",
         "At-least-once consumers."),
        ("leader_election", "Leader Election", "distributed_systems", "consensus", ["leader election", "distributed lock"],
         "Single coordinator via lease/raft/etcd.",
         "Cron or write leader workloads."),
        ("cap_tradeoffs", "CAP Tradeoffs", "distributed_systems", "theory", ["cap theorem", "partition tolerance"],
         "During partition, choose consistency vs availability.",
         "Designing multi-region systems."),
        ("nosql_document", "Document Database", "databases", "nosql", ["mongodb", "document db"],
         "JSON-like documents with flexible schema.",
         "Rapid schema evolution; not ideal for all joins."),
        ("caching_http", "HTTP Caching", "performance", "cache", ["http cache", "cache-control", "etag"],
         "Cache responses with Cache-Control and validators.",
         "Read-heavy public GET endpoints."),
        ("load_balancer", "Load Balancer", "networking", "lb", ["load balancer", "alb", "nlb"],
         "Distribute traffic across healthy instances.",
         "Horizontally scaled stateless APIs."),
        ("websocket_realtime", "WebSockets", "backend", "realtime", ["websocket", "ws", "realtime"],
         "Full-duplex channel over HTTP upgrade.",
         "Live dashboards, chat, market data streams."),
        ("message_queue", "Message Queue", "messaging", "queue", ["message queue", "queue", "broker"],
         "Asynchronous work via durable queues.",
         "Decouple producers and consumers."),
        ("pub_sub", "Pub/Sub", "messaging", "pubsub", ["pubsub", "publish subscribe", "topic"],
         "Fan-out events to multiple subscribers.",
         "Event notifications across services."),
        ("dark_mode_ui", "Dark Mode UI", "frontend", "ui", ["dark mode", "theme"],
         "Alternate color tokens for low-light UX.",
         "User preference and accessibility."),
        ("accessibility_wcag", "Accessibility WCAG", "frontend", "a11y", ["wcag", "accessibility", "a11y"],
         "Meet WCAG contrast/focus/semantic requirements.",
         "Public web apps."),
        ("e2e_testing", "E2E Testing", "testing", "e2e", ["e2e", "end to end test"],
         "Test full user journeys in near-prod environment.",
         "Critical flows before release."),
        ("contract_testing", "Contract Testing", "testing", "contract", ["contract test", "pact"],
         "Consumer-driven contracts between services.",
         "Microservices integration."),
        ("property_based_testing", "Property-Based Testing", "testing", "property", ["property test", "hypothesis"],
         "Generate inputs to verify invariants.",
         "Parsing, pricing, serialization logic."),
        ("monolith_modular", "Modular Monolith", "software_architecture", "style", ["modular monolith"],
         "Single deploy with clear internal module boundaries.",
         "Before splitting microservices."),
        ("clean_architecture", "Clean Architecture", "software_architecture", "pattern", ["clean architecture", "layers"],
         "Dependencies point inward; domain at center.",
         "Long-lived business apps."),
        ("hexagonal_architecture", "Hexagonal Architecture", "software_architecture", "pattern", ["hexagonal", "ports adapters"],
         "Ports and adapters isolate domain from IO.",
         "Testable domain core."),
        ("bulkhead_pattern", "Bulkhead Pattern", "software_architecture", "pattern", ["bulkhead"],
         "Isolate thread pools per dependency.",
         "Prevent total exhaustion from one slow dep."),
        ("sidecar_pattern", "Sidecar Pattern", "software_architecture", "pattern", ["sidecar"],
         "Helper container alongside main workload.",
         "Service mesh proxies, log agents."),
        ("bff_pattern", "Backend for Frontend", "software_architecture", "pattern", ["bff", "backend for frontend"],
         "Tailored API per client channel.",
         "Mobile vs web different aggregation needs."),
        ("strangler_fig", "Strangler Fig", "software_architecture", "migration", ["strangler fig"],
         "Gradually replace legacy by routing slices to new system.",
         "Legacy modernization."),
        ("prompt_engineering", "Prompt Engineering", "ai_infrastructure", "llm", ["prompt engineering", "prompt design"],
         "Structure prompts, examples, and guardrails for LLMs.",
         "All LLM features."),
        ("embedding_search", "Embedding Search", "ai_infrastructure", "embedding", ["embedding", "vector search"],
         "Semantic similarity via vector indexes.",
         "RAG retrieval step."),
        ("fine_tuning", "Fine Tuning", "machine_learning", "training", ["fine tuning", "finetune"],
         "Adapt base model weights to domain data.",
         "When prompt-only is insufficient."),
        ("data_pipeline_etl", "ETL Pipeline", "data_engineering", "etl", ["etl", "data pipeline"],
         "Extract-transform-load batch pipelines.",
         "Warehouse analytics inputs."),
        ("data_lineage", "Data Lineage", "data_engineering", "governance", ["data lineage"],
         "Track origin and transforms of datasets.",
         "Compliance and debugging."),
        ("stream_processing", "Stream Processing", "data_engineering", "streaming", ["stream processing", "kafka streams"],
         "Continuous processing of event streams.",
         "Real-time analytics."),
        ("schema_registry", "Schema Registry", "data_engineering", "schema", ["schema registry", "avro schema"],
         "Versioned schemas for serialized events.",
         "Kafka/Avro ecosystems."),
        ("mobile_offline", "Mobile Offline Sync", "mobile", "offline", ["offline sync", "mobile offline"],
         "Queue mutations when offline; reconcile on reconnect.",
         "Mobile field apps."),
        ("push_notifications", "Push Notifications", "mobile", "push", ["push notification", "fcm", "apns"],
         "Deliver notifications via platform gateways.",
         "Mobile engagement."),
        ("gitops", "GitOps", "ci_cd", "gitops", ["gitops", "argocd"],
         "Git as source of truth for cluster state.",
         "Kubernetes deployments."),
        ("canary_deploy", "Canary Deployment", "ci_cd", "deploy", ["canary", "canary deployment"],
         "Route small traffic % to new version before full rollout.",
         "Risky releases."),
        ("blue_green_deploy", "Blue-Green Deployment", "ci_cd", "deploy", ["blue green", "blue-green"],
         "Two environments switch traffic atomically.",
         "Zero-downtime deploys."),
        ("sbom_supply_chain", "SBOM", "ci_cd", "security", ["sbom", "supply chain"],
         "Software bill of materials for dependencies.",
         "Security compliance."),
        ("profiling_cpu", "CPU Profiling", "performance", "profiling", ["cpu profiling", "py-spy", "pprof"],
         "Find hot functions consuming CPU.",
         "Latency regressions."),
        ("memory_profiling", "Memory Profiling", "performance", "profiling", ["memory profiling", "heap"],
         "Find leaks and allocation hotspots.",
         "OOM incidents."),
        ("cdn_edge", "CDN", "performance", "cdn", ["cdn", "cloudfront", "edge cache"],
         "Cache static assets close to users.",
         "Global web apps."),
        ("dns_tls", "DNS", "networking", "dns", ["dns", "domain name"],
         "Name resolution and TTL planning.",
         "Every public service."),
        ("mtls_service", "mTLS", "networking", "mtls", ["mtls", "mutual tls"],
         "Both client and server present certificates.",
         "Service mesh internal traffic."),
        ("vlan_subnet", "VPC Subnet", "cloud", "network", ["vpc", "subnet", "security group"],
         "Network isolation in cloud accounts.",
         "All cloud deployments."),
        ("object_storage_s3", "Object Storage", "cloud", "storage", ["s3", "object storage", "blob"],
         "Durable objects with key-based access.",
         "Files, backups, data lake."),
        ("server_sent_events", "Server-Sent Events", "backend", "streaming", ["sse", "server sent events"],
         "One-way server push over HTTP.",
         "Live feeds simpler than WebSockets."),
        ("graphql_n_plus_one", "GraphQL N+1", "apis", "graphql", ["graphql n+1", "dataloader"],
         "Batch/resolver pattern to avoid N+1 queries.",
         "GraphQL with relational backing."),
        ("api_pagination_offset", "Offset Pagination", "apis", "pagination", ["offset pagination", "page page_size"],
         "Simple page/page_size; poor at large offsets.",
         "Admin tables only at small scale."),
        ("optimistic_ui", "Optimistic UI", "frontend", "ux", ["optimistic ui", "optimistic update"],
         "Update UI before server ack; rollback on failure.",
         "Snappy UX for mutations."),
        ("error_boundary", "React Error Boundary", "frontend", "react", ["error boundary"],
         "Catch render errors and show fallback UI.",
         "Prevent white screen of death."),
        ("code_splitting", "Code Splitting", "frontend", "bundle", ["code splitting", "lazy load route"],
         "Split bundles per route/feature.",
         "Large SPAs."),
        ("websocket_backpressure", "Backpressure", "messaging", "flow", ["backpressure", "pressure"],
         "Slow consumers must not unbounded-buffer producers.",
         "Streaming systems."),
        ("poison_message", "Poison Message", "messaging", "dlq", ["poison message", "poison pill"],
         "Message that always fails processing.",
         "Move to DLQ after N tries."),
        ("ordering_guarantee", "Message Ordering", "messaging", "ordering", ["fifo", "ordering guarantee"],
         "Per-partition ordering vs global ordering cost.",
         "Financial event processing."),
        ("exactly_once", "Exactly-Once Semantics", "messaging", "semantics", ["exactly once"],
         "End-to-end exactly-once is hard; usually at-least-once + idempotency.",
         "Payment pipelines."),
        ("write_skew", "Write Skew", "databases", "anomaly", ["write skew"],
         "Serializable anomaly under concurrent transactions.",
         "Inventory/finance counters."),
        ("phantom_read", "Phantom Read", "databases", "anomaly", ["phantom read"],
         "New rows appear in repeated range query.",
         "Choosing isolation level."),
        ("partial_index", "Partial Index", "databases", "index", ["partial index"],
         "Index subset of rows matching predicate.",
         "Large table with hot subset."),
        ("materialized_view", "Materialized View", "databases", "view", ["materialized view"],
         "Precomputed query results refreshed on schedule.",
         "Dashboard aggregates."),
        ("read_replica", "Read Replica", "databases", "replication", ["read replica", "replica lag"],
         "Scale reads; accept replication lag.",
         "Read-heavy workloads."),
        ("connection_limit_db", "DB Connection Limits", "databases", "ops", ["max connections", "too many connections"],
         "Exhaustion when pool * instances > max_connections.",
         "Scale-out app tier."),
        ("slow_query_log", "Slow Query Log", "databases", "ops", ["slow query", "slow query log"],
         "Find queries exceeding threshold.",
         "Performance incidents."),
        ("password_hashing", "Password Hashing", "security", "crypto", ["bcrypt", "argon2", "password hash"],
         "Store password hashes not plaintext.",
         "User credential storage."),
        ("mfa", "Multi-Factor Authentication", "security", "auth", ["mfa", "2fa", "totp"],
         "Second factor beyond password.",
         "Sensitive accounts."),
        ("api_key_rotation", "API Key Rotation", "security", "secrets", ["api key rotation"],
         "Rotate keys on schedule and incident.",
         "Service integrations."),
        ("certificate_pinning", "Certificate Pinning", "security", "mobile", ["certificate pinning"],
         "Pin expected server cert/public key in mobile apps.",
         "High-security mobile clients."),
        ("session_fixation", "Session Fixation", "security", "session", ["session fixation"],
         "Issue new session ID after login.",
         "Cookie-based sessions."),
        ("idor", "IDOR", "security", "authz", ["idor", "insecure direct object"],
         "Authorize per-object not only authentication.",
         "Multi-tenant APIs."),
        ("content_security_policy", "Content Security Policy", "security", "web", ["csp", "content security policy"],
         "Restrict script/style sources to mitigate XSS.",
         "Web frontends."),
        ("same_site_cookie", "SameSite Cookies", "security", "web", ["samesite", "same site cookie"],
         "CSRF mitigation via cookie attributes.",
         "Browser sessions."),
        ("log_redaction", "Log Redaction", "observability", "logging", ["pii redaction", "log scrubbing"],
         "Remove secrets/PII from log fields.",
         "Compliance logging."),
        ("slo_error_budget", "SLO Error Budget", "observability", "slo", ["slo", "error budget"],
         "Allowed unreliability before freeze features.",
         "SRE practice."),
        ("alert_fatigue", "Alert Fatigue", "observability", "alerting", ["alert fatigue"],
         "Too many low-signal pages.",
         "On-call health."),
        ("cardinality_explosion", "Metric Cardinality", "observability", "metrics", ["cardinality", "high cardinality"],
         "Unbounded label values explode storage cost.",
         "Prometheus/OTel metrics design."),
        ("trace_sampling", "Trace Sampling", "observability", "tracing", ["trace sampling"],
         "Sample traces to control cost while keeping errors.",
         "High-traffic services."),
        ("chaos_engineering", "Chaos Engineering", "testing", "chaos", ["chaos engineering", "chaos monkey"],
         "Inject faults to verify resilience.",
         "Mature distributed systems."),
        ("load_testing", "Load Testing", "testing", "load", ["load test", "k6", "locust"],
         "Verify SLOs under expected peak load.",
         "Before major launches."),
        ("smoke_test", "Smoke Test", "testing", "smoke", ["smoke test"],
         "Minimal path verifying deploy viability.",
         "Post-deploy gate."),
        ("static_analysis", "Static Analysis", "testing", "static", ["static analysis", "lint", "sast"],
         "Analyze code without running.",
         "CI security/quality gates."),
        ("dependency_scanning", "Dependency Scanning", "ci_cd", "security", ["dependabot", "sca", "snyk"],
         "Scan third-party CVEs.",
         "Every build."),
        ("container_image_scan", "Container Scanning", "ci_cd", "security", ["image scan", "trivy"],
         "Scan images for OS/package CVEs.",
         "Container deploys."),
        ("horizontal_pod_autoscaler", "HPA", "cloud", "k8s", ["hpa", "horizontal pod autoscaler"],
         "Scale pods on CPU/custom metrics.",
         "Variable load services."),
        ("config_map_secret", "ConfigMap and Secret", "cloud", "k8s", ["configmap", "kubernetes secret"],
         "Inject config and secrets into pods.",
         "12-factor k8s apps."),
        ("ingress_controller", "Ingress Controller", "cloud", "k8s", ["ingress", "nginx ingress"],
         "HTTP routing into cluster.",
         "Public k8s services."),
        ("statefulset", "StatefulSet", "cloud", "k8s", ["statefulset", "stable network id"],
         "Stable pod identity and storage.",
         "Databases on k8s (careful)."),
        ("pod_disruption_budget", "Pod Disruption Budget", "cloud", "k8s", ["pdb", "pod disruption budget"],
         "Maintain min available during drains.",
         "HA services."),
        ("vwap", "VWAP", "trading", "indicator", ["vwap", "volume weighted"],
         "Volume-weighted average price benchmark.",
         "Execution quality measurement."),
        ("market_order", "Market Order", "trading", "execution", ["market order"],
         "Execute immediately at best available price.",
         "Liquidity urgent exits."),
        ("limit_order", "Limit Order", "trading", "execution", ["limit order"],
         "Execute at specified price or better.",
         "Price-controlled entries."),
        ("slippage_model", "Slippage Model", "trading", "sim", ["slippage", "slippage model"],
         "Model price impact in simulation.",
         "Realistic backtests."),
        ("order_book", "Order Book", "trading", "market_data", ["order book", "level2"],
         "Bid/ask depth-driven microstructure.",
         "HFT and realistic sim."),
        ("sharpe_ratio", "Sharpe Ratio", "trading", "metric", ["sharpe", "sharpe ratio"],
         "Risk-adjusted return metric.",
         "Strategy comparison (with caution)."),
        ("max_drawdown", "Max Drawdown", "trading", "metric", ["max drawdown", "drawdown"],
         "Peak-to-trough loss on equity curve.",
         "Risk reporting."),
        ("position_sizing", "Position Sizing", "trading", "risk", ["position sizing", "risk per trade"],
         "Capital allocation per trade from risk rules.",
         "Risk-managed trading systems."),
        ("options_greeks", "Options Greeks", "quant_finance", "derivatives", ["greeks", "delta", "gamma"],
         "Sensitivity of option price to inputs.",
         "Options trading systems."),
        ("implied_volatility", "Implied Volatility", "quant_finance", "vol", ["implied vol", "iv"],
         "Market-implied volatility from option prices.",
         "Options analytics."),
        ("pairs_trading", "Pairs Trading", "trading", "strategy", ["pairs trade", "stat arb pair"],
         "Trade spread between correlated instruments.",
         "Market-neutral strategies."),
        ("stop_loss", "Stop Loss", "trading", "risk", ["stop loss", "stop-loss"],
         "Exit when price crosses threshold.",
         "Risk management rules."),
        ("take_profit", "Take Profit", "trading", "risk", ["take profit", "profit target"],
         "Exit when profit target reached.",
         "Bracket orders."),
        ("paper_trading", "Paper Trading", "trading", "sim", ["paper trading", "paper trade"],
         "Simulated trading without capital risk.",
         "Strategy validation before live."),
        ("live_trading", "Live Trading", "trading", "execution", ["live trading", "live execution"],
         "Real orders to venue/broker.",
         "Production trading path."),
    ]
    out: List[Dict[str, Any]] = []
    for row in specs:
        cid, name, domain, cat, aliases, desc, when = row
        refs = [f"atlas://curated/{domain}/{cid}"]
        if domain in ("security", "authentication", "authorization"):
            refs.append("https://cheatsheetseries.owasp.org/")
        out.append(
            _entry(
                cid, name, domain, cat, "curated_deep",
                aliases, desc, when, refs,
                path_keywords=[cid.split("_")[0]] + aliases[:2],
            )
        )
    return out


def build_phase128_catalog() -> List[Dict[str, Any]]:
    items = _source_backed() + _curated_deep()
    # Deduplicate by concept_id (source_backed wins)
    by_id: Dict[str, Dict[str, Any]] = {}
    for raw in items:
        by_id[raw["concept_id"]] = raw
    return list(by_id.values())


PHASE128_CATALOG: List[Dict[str, Any]] = build_phase128_catalog()

assert len(PHASE128_CATALOG) >= 150, len(PHASE128_CATALOG)
assert sum(1 for c in PHASE128_CATALOG if c.get("concept_quality_score") == "source_backed") >= 50
