; Auto-generated by packaging/installer/installer_build.ps1
#define MyAppVersion "phase146b-true-beta-blocker-fixes"
#define MyAppVersionInfo "1.0.0.0"
#define MyBuildDate "2026-06-04"
#define MyCommitHash "6c7e929c"
