# Atlas — Inno Setup installer build (Phase 152)
# Usage:
#   .\packaging\installer\installer_build.ps1
#   .\packaging\installer\installer_build.ps1 -SkipPackage
#   .\packaging\installer\installer_build.ps1 -SkipCompile

param(
    [switch]$SkipPackage,
    [switch]$SkipCompile
)

$ErrorActionPreference = "Stop"
$InstallerDir = $PSScriptRoot
$Root = (Resolve-Path (Join-Path $InstallerDir "..\..")).Path
$Staging = Join-Path $InstallerDir "staging"
$OutputDir = Join-Path $InstallerDir "output"
$AssetsDir = Join-Path $InstallerDir "assets"
$DistAtlas = Join-Path $Root "dist\Atlas"
$AtlasExe = Join-Path $DistAtlas "Atlas.exe"
$PyBuild = Join-Path $Root "packaging\pyinstaller\build_atlas_exe.ps1"

function Write-InnoVersionDefines {
    $version = "1.0.0-beta"
    $apiFile = Join-Path $Root "jarvis_desktop\api.py"
    if (Test-Path $apiFile) {
        $m = Select-String -Path $apiFile -Pattern 'PRODUCT_VERSION\s*=\s*"([^"]+)"' | Select-Object -First 1
        if ($m) { $version = $m.Matches[0].Groups[1].Value }
    }
    $commit = "unknown"
    try {
        Push-Location $Root
        $hash = git rev-parse --short HEAD 2>$null
        if ($hash) { $commit = $hash }
    } catch { }
    finally { Pop-Location }
    $semver = "1.0.0.0"
    $parts = ($version -replace '[^0-9.]', '.').Split('.') | Where-Object { $_ -match '^\d+$' }
    if ($parts.Count -ge 1) {
        $nums = @("1", "0", "0", "0")
        for ($i = 0; $i -lt [Math]::Min(4, $parts.Count); $i++) { $nums[$i] = $parts[$i] }
        $semver = ($nums[0..3] -join '.')
    }
    $buildDate = Get-Date -Format "yyyy-MM-dd"
    $content = @"
; Auto-generated by packaging/installer/installer_build.ps1
#define MyAppVersion "$version"
#define MyAppVersionInfo "$semver"
#define MyBuildDate "$buildDate"
#define MyCommitHash "$commit"
"@
    $verPath = Join-Path $InstallerDir "generated_version.iss"
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($verPath, $content, $utf8)
}

function Ensure-Icon {
    $icon = Join-Path $AssetsDir "atlas.ico"
    $legacy = Join-Path $Root "installer\assets\jarvis.ico"
    New-Item -ItemType Directory -Path $AssetsDir -Force | Out-Null
    if (-not (Test-Path $icon) -and (Test-Path $legacy)) {
        Copy-Item -LiteralPath $legacy -Destination $icon -Force
    }
}

Write-Host "Atlas installer build (Phase 152)" -ForegroundColor Cyan
Write-InnoVersionDefines
Ensure-Icon

if (-not $SkipPackage) {
    & $PyBuild -Clean
    if ($LASTEXITCODE -ne 0) { throw "PyInstaller build failed with exit code $LASTEXITCODE" }
}

if (-not (Test-Path $AtlasExe)) {
    throw "Missing packaged Atlas executable: $AtlasExe"
}

if (Test-Path $Staging) { Remove-Item -LiteralPath $Staging -Recurse -Force }
New-Item -ItemType Directory -Path $Staging, $OutputDir -Force | Out-Null
Copy-Item -Path (Join-Path $DistAtlas "*") -Destination $Staging -Recurse -Force
New-Item -ItemType Directory -Path (Join-Path $Staging "assets") -Force | Out-Null
if (Test-Path (Join-Path $AssetsDir "atlas.ico")) {
    Copy-Item -LiteralPath (Join-Path $AssetsDir "atlas.ico") -Destination (Join-Path $Staging "assets\atlas.ico") -Force
}

Write-Host "Staged: $Staging" -ForegroundColor Green

# Phase 157 — installer self-test (pre-compile): verify the staged payload and
# that the installer script declares the shortcuts the self-test will look for.
function Test-StagedInstaller {
    $issues = @()
    $stagedExe = Join-Path $Staging "Atlas.exe"
    if (-not (Test-Path $stagedExe)) { $issues += "missing staged Atlas.exe ($stagedExe)" }
    $issText = Get-Content -Raw (Join-Path $InstallerDir "Atlas.iss")
    if ($issText -notmatch "autodesktop") { $issues += "Atlas.iss does not create a desktop shortcut" }
    if ($issText -notmatch "\{group\}") { $issues += "Atlas.iss does not create a Start menu shortcut" }
    if ($issText -notmatch "InfoBeforeFile") { $issues += "Atlas.iss does not show beta install notes" }
    $staticSupport = Join-Path $Staging "_internal\jarvis_desktop\static\support.html"
    if (-not (Test-Path $staticSupport)) {
        $staticSupport = Get-ChildItem -Path $Staging -Recurse -Filter "support.html" -ErrorAction SilentlyContinue | Select-Object -First 1
        if (-not $staticSupport) { $issues += "support.html missing from staged payload" }
    }
    if ($issues.Count -gt 0) {
        Write-Host "Installer self-test FAILED:" -ForegroundColor Red
        $issues | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
        throw "Installer self-test failed with $($issues.Count) issue(s)."
    }
    Write-Host "Installer self-test passed (staged payload + shortcuts + notes)." -ForegroundColor Green
}
Test-StagedInstaller

if ($SkipCompile) {
    Write-Host "SkipCompile - staging only." -ForegroundColor Yellow
    exit 0
}

$Iscc = @(
    (Join-Path $Root ".phase152_inno\ISCC.exe"),
    (Join-Path $Root ".phase150_inno\ISCC.exe"),
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "$env:ProgramFiles\Inno Setup 6\ISCC.exe",
    "ISCC.exe"
) | Where-Object { Test-Path $_ } | Select-Object -First 1

if (-not $Iscc) {
    Write-Host "Inno Setup (ISCC.exe) not found. Staging is ready at $Staging" -ForegroundColor Yellow
    Write-Host "Install Inno Setup 6, then: ISCC.exe packaging\installer\Atlas.iss"
    exit 2
}

Push-Location $InstallerDir
try {
    & $Iscc (Join-Path $InstallerDir "Atlas.iss")
    if ($LASTEXITCODE -ne 0) { throw "ISCC failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

$setup = Join-Path $OutputDir "Atlas_Setup.exe"
if (-not (Test-Path $setup)) {
    throw "Expected installer not found: $setup"
}
$legacyOut = Join-Path $Root "installer\output\Atlas_Setup.exe"
New-Item -ItemType Directory -Path (Split-Path $legacyOut) -Force | Out-Null
Copy-Item -LiteralPath $setup -Destination $legacyOut -Force
$item = Get-Item -LiteralPath $setup
$setupMb = [Math]::Round($item.Length / 1048576, 2)
Write-Host ("Built: {0} ({1} MB)" -f $setup, $setupMb) -ForegroundColor Green
Write-Host "Copied: $legacyOut" -ForegroundColor DarkGray
