# Atlas  -  Inno Setup installer build
# Usage:
#   .\packaging\installer\installer_build.ps1
#   .\packaging\installer\installer_build.ps1 -SkipPackage
#   .\packaging\installer\installer_build.ps1 -SkipCompile

param(
    [switch]$SkipPackage,
    [switch]$SkipCompile,
    # Keep account packaging available only for a future account-enabled
    # release; the analytics-only RC must not include AtlasAccounts.exe.
    [switch]$IncludeAccounts
)

$ErrorActionPreference = "Stop"
$_bootstrapDir = $PSScriptRoot
if (-not $_bootstrapDir -and $PSCommandPath) { $_bootstrapDir = Split-Path -Parent $PSCommandPath }
if (-not $_bootstrapDir) { throw "Cannot resolve installer script path. Run .\packaging\installer\installer_build.ps1 directly." }
$Common = Join-Path (Split-Path -Parent $_bootstrapDir) "packaging_common.ps1"
if (-not (Test-Path -LiteralPath $Common)) { throw "Missing packaging module: $Common" }
. $Common

$InstallerDir = $_bootstrapDir
$Root = Get-RepoRootFrom -ScriptDir $InstallerDir -LevelsUp 2
Assert-AtlasBuildRoot -Root $Root
$Staging = Join-PathSafe $InstallerDir "staging"
$OutputDir = Join-PathSafe $InstallerDir "output"
$AssetsDir = Join-PathSafe $InstallerDir "assets"
$DistAtlas = Join-PathSafe $Root "dist\Atlas"
$AtlasExe = Join-PathSafe $DistAtlas "Atlas.exe"
$PyBuild = Join-PathSafe $Root "packaging\pyinstaller\build_atlas_exe.ps1"

function Write-InnoVersionDefines {
    $version = "1.0.0"
    $productFile = Join-Path $Root "atlas_desktop\product_info.py"
    if (Test-Path $productFile) {
        $m = Select-String -Path $productFile -Pattern 'PRODUCT_VERSION\s*=\s*"([^"]+)"' | Select-Object -First 1
        if ($m) { $version = $m.Matches[0].Groups[1].Value }
    }
    $commit = "unknown"
    try {
        Push-Location $Root
        $hash = git rev-parse HEAD 2>$null
        if ($hash) { $commit = $hash }
    } catch { }
    finally { Pop-Location }
    $semver = "1.0.0.0"
    $parts = ($version -replace '[^0-9.]', '.').Split('.') | Where-Object { $_ -match '^\d+$' }
    if ($parts.Count -ge 1) {
        $nums = @("1", "0", "0", "0")
        for ($i = 0; $i -lt [Math]::Min(4, $parts.Count); $i++) { $nums[$i] = $parts[$i] }
        $semver = ($nums[0..3] -join '.')
    }
    $buildDate = Get-Date -Format "yyyy-MM-dd"
    $content = @"
; Auto-generated by packaging/installer/installer_build.ps1
#define MyAppVersion "$version"
#define MyAppVersionInfo "$semver"
#define MyBuildDate "$buildDate"
#define MyCommitHash "$commit"
"@
    $verPath = Join-Path $InstallerDir "generated_version.iss"
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($verPath, $content, $utf8)
}

function Ensure-Icon {
    $icon = Join-Path $AssetsDir "atlas.ico"
    New-Item -ItemType Directory -Path $AssetsDir -Force | Out-Null
    if (-not (Test-Path $icon)) {
        throw "Missing installer icon: $icon"
    }
}

Write-Host "Atlas installer build - source: $Root" -ForegroundColor Cyan
Write-InnoVersionDefines
Ensure-Icon

if (-not $SkipPackage) {
    if ($IncludeAccounts) { & $PyBuild -Clean -IncludeAccounts }
    else { & $PyBuild -Clean }
    if ($LASTEXITCODE -ne 0) { throw "PyInstaller build failed with exit code $LASTEXITCODE" }
}

if (-not (Test-Path $AtlasExe)) {
    throw "Missing packaged Atlas executable: $AtlasExe"
}

if (Test-Path $Staging) { Remove-Item -LiteralPath $Staging -Recurse -Force }
New-Item -ItemType Directory -Path $Staging, $OutputDir -Force | Out-Null
Copy-Item -Path (Join-Path $DistAtlas "*") -Destination $Staging -Recurse -Force
New-Item -ItemType Directory -Path (Join-Path $Staging "assets") -Force | Out-Null
if (Test-Path (Join-Path $AssetsDir "atlas.ico")) {
    Copy-Item -LiteralPath (Join-Path $AssetsDir "atlas.ico") -Destination (Join-Path $Staging "assets\atlas.ico") -Force
}

Write-Host "Staged: $Staging" -ForegroundColor Green

function Test-StagedInstaller {
    $issues = @()
    $stagedExe = Join-Path $Staging "Atlas.exe"
    if (-not (Test-Path $stagedExe)) { $issues += "missing staged Atlas.exe ($stagedExe)" }
    $stagedAccounts = Join-Path $Staging "accounts\AtlasAccounts.exe"
    if ($IncludeAccounts -and -not (Test-Path $stagedAccounts)) { $issues += "missing bundled accounts service ($stagedAccounts)" }
    if (-not $IncludeAccounts -and (Test-Path $stagedAccounts)) { $issues += "accounts service must not be bundled in analytics-only RC" }
    $issText = Get-Content -Raw (Join-Path $InstallerDir "Atlas.iss")
    if ($issText -notmatch "autodesktop") { $issues += "Atlas.iss does not create a desktop shortcut" }
    if ($issText -notmatch "\{group\}") { $issues += "Atlas.iss does not create a Start menu shortcut" }
    if ($issText -notmatch "InfoBeforeFile") { $issues += "Atlas.iss does not show install notes" }
    $staticSupport = Join-Path $Staging "_internal\atlas_desktop\static\support.html"
    if (-not (Test-Path $staticSupport)) {
        $staticSupport = Get-ChildItem -Path $Staging -Recurse -Filter "support.html" -ErrorAction SilentlyContinue | Select-Object -First 1
        if (-not $staticSupport) { $issues += "support.html missing from staged payload" }
    }
    $indexPath = Find-StagedIndexHtml -StagingRoot $Staging
    if (-not $indexPath) {
        $issues += "index.html missing from staged atlas_desktop/static payload"
    } else {
        $uxIssues = Test-HnLaunchUxPayload -IndexPath $indexPath
        foreach ($ux in $uxIssues) { $issues += "HN launch UX: $ux" }
    }
    if ($issues.Count -gt 0) {
        Write-Host "Installer self-test FAILED:" -ForegroundColor Red
        $issues | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
        throw "Installer self-test failed with $($issues.Count) issue(s)."
    }
    Write-Host "Installer self-test passed (HN launch UX + staged payload + shortcuts + notes)." -ForegroundColor Green
}
Test-StagedInstaller

# Release gate: refuse to package a tree whose metadata names the build
# machine. v1.0.5 shipped the developer's source_root to every user; this makes
# a repeat impossible rather than merely unlikely.
$LeakScanner = Join-PathSafe $Root "scripts\scan_build_metadata_leaks.py"
if (Test-Path -LiteralPath $LeakScanner) {
    & py -3 $LeakScanner $Staging
    if ($LASTEXITCODE -ne 0) {
        throw "Build metadata leak scan failed  -  refusing to package. See the findings above."
    }
} else {
    throw "Missing release gate: $LeakScanner"
}

if ($SkipCompile) {
    Write-Host "SkipCompile - staging only." -ForegroundColor Yellow
    exit 0
}

$Iscc = Find-InnoSetupCompiler -Root $Root
if (-not $Iscc) {
    Write-Host "Inno Setup (ISCC.exe) not found. Staging is ready at $Staging" -ForegroundColor Yellow
    Write-Host "Install Inno Setup 6, then: ISCC.exe packaging\installer\Atlas.iss"
    exit 2
}

Push-Location $InstallerDir
try {
    & $Iscc (Join-Path $InstallerDir "Atlas.iss")
    if ($LASTEXITCODE -ne 0) { throw "ISCC failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

$version = Get-AtlasProductVersion -Root $Root
$setup = Join-Path $OutputDir "Atlas-Setup-$version.exe"
if (-not (Test-Path $setup)) {
    throw "Expected installer not found: $setup"
}
$item = Get-Item -LiteralPath $setup
$setupMb = [Math]::Round($item.Length / 1048576, 2)
Write-Host ("Built: {0} ({1} MB)" -f $setup, $setupMb) -ForegroundColor Green

# Always regenerate the SHA256 sidecar so it can never go stale against the artifact.
$hash = (Get-FileHash -LiteralPath $setup -Algorithm SHA256).Hash
[System.IO.File]::WriteAllText("$setup.sha256", $hash, (New-Object System.Text.UTF8Encoding $false))
Write-Host ("SHA256: {0}" -f $hash) -ForegroundColor Green

# The exact three values websites/atlas-web/app/_config.ts needs. Printing them
# together is what makes "paste the build output into the release constant" a
# mechanical step rather than three separate chances to transcribe one wrong.
Write-Host ""
Write-Host "Paste into CURRENT_WINDOWS_RELEASE (app/_config.ts):" -ForegroundColor Cyan
Write-Host ("  version:   `"{0}`"" -f $version)
Write-Host ("  filename:  `"{0}`"" -f (Split-Path -Leaf $setup))
Write-Host ("  sha256:    `"{0}`"" -f $hash)
Write-Host ("  sizeBytes: {0}" -f $item.Length)
