"""Generate AGENTS.md / CLAUDE.md from the canonical repository memory.

These files are OUTPUTS of Atlas memory, never inputs. Atlas owns a delimited
managed block; human-authored content outside the block is never touched.

Source of truth: repository_memory (one canonical store). No separate memory path.
"""
from __future__ import annotations

import hashlib
import os
from typing import Any, Dict, List, Optional, Tuple

MANAGED_BEGIN = "<!-- ATLAS:BEGIN MANAGED BLOCK -->"
MANAGED_END = "<!-- ATLAS:END MANAGED BLOCK -->"
_NOTE = (
    "<!-- Generated by Atlas from repository memory. Do not edit inside this block; "
    "changes here are overwritten on regeneration. Edit outside the block freely. -->"
)


# --------------------------------------------------------------------------
# Managed-block engine (deterministic; preserves user content)
# --------------------------------------------------------------------------
def _norm(text: str) -> str:
    return "\n".join(line.rstrip() for line in (text or "").splitlines()).strip()


def block_signature(text: str) -> str:
    return hashlib.sha256(_norm(text).encode("utf-8", errors="ignore")).hexdigest()


def wrap_block(body: str) -> str:
    return f"{MANAGED_BEGIN}\n{_NOTE}\n\n{body.strip()}\n{MANAGED_END}"


def extract_block(text: str) -> Optional[str]:
    """Return the full managed block (markers included) or None if absent."""
    if MANAGED_BEGIN not in text or MANAGED_END not in text:
        return None
    inner = text.split(MANAGED_BEGIN, 1)[1].split(MANAGED_END, 1)[0]
    return f"{MANAGED_BEGIN}{inner}{MANAGED_END}"


def apply_managed_block(existing: str, body: str) -> str:
    """Insert/replace the managed block, leaving all human content untouched."""
    block = wrap_block(body)
    if MANAGED_BEGIN in existing and MANAGED_END in existing:
        pre = existing.split(MANAGED_BEGIN, 1)[0]
        post = existing.split(MANAGED_END, 1)[1]
        return f"{pre}{block}{post}"
    if not existing:
        return block + "\n"
    sep = "\n" if existing.endswith("\n") else "\n\n"
    return f"{existing}{sep}{block}\n"


def estimate_tokens(text: str) -> int:
    return max(0, round(len(text or "") / 4))


# --------------------------------------------------------------------------
# Rendering: memory -> concise agent context (deterministic from memory)
# --------------------------------------------------------------------------
def _ctx(memory: Dict[str, Any]) -> Dict[str, Any]:
    return (memory or {}).get("agent_context") or {}


def _commands_lines(commands: Dict[str, str]) -> List[str]:
    order = [("build", "Build"), ("test", "Test"), ("run", "Run"), ("lint", "Lint"), ("deploy", "Deploy")]
    lines: List[str] = []
    for key, label in order:
        value = commands.get(key)
        if not value:
            continue
        if str(value).upper() == "UNKNOWN":
            lines.append(f"- {label}: UNKNOWN")
        else:
            lines.append(f"- {label}: `{value}`")
    return lines


def _package_command_text(commands: Dict[str, str]) -> str:
    parts: List[str] = []
    label_map = {
        "test": "test",
        "build": "build",
        "lint": "lint",
        "run": "run",
        "type": "type",
        "integration_tests": "integration",
        "check_imports": "imports",
        "check-lock": "lock check",
    }
    for key in ("test", "build", "lint", "type", "integration_tests", "check_imports", "check-lock", "run"):
        value = commands.get(key)
        if value and str(value).upper() != "UNKNOWN":
            parts.append(f"{label_map.get(key, key)} `{value}`")
    return "; ".join(parts)


def _all_primary_commands_unknown(commands: Dict[str, str]) -> bool:
    primary = [str(commands.get(k, "")).upper() for k in ("build", "test", "run", "lint")]
    return bool(primary) and all(v in {"", "UNKNOWN"} for v in primary)


def generate_agents_md(memory: Dict[str, Any]) -> str:
    """AGENTS.md managed-block body — concise, token-bounded, agent-useful."""
    c = _ctx(memory)
    name = memory.get("repo_name", "repository")
    out: List[str] = [f"# {name}"]

    if c.get("project_summary"):
        out.append(c["project_summary"])
    if c.get("stack"):
        out.append(f"**Stack:** {', '.join(c['stack'])}")

    out.append("\n## Architecture")
    out.append(c.get("architecture_summary", "Not analyzed yet."))

    if c.get("key_subsystems"):
        out.append("\n## Key subsystems")
        for s in c["key_subsystems"]:
            purpose = s.get("purpose") or "UNKNOWN"
            confidence = s.get("confidence") or "low"
            reps = s.get("representative_files") or []
            rep_text = f" Representative files: {', '.join(reps[:3])}." if reps else ""
            out.append(f"- {s['name']} ({s.get('files', 0)} files, {confidence}): {purpose}.{rep_text}")

    if c.get("packages"):
        out.append("\n## Workspace packages")
        for p in c["packages"]:
            name = p.get("name") or p.get("path")
            owner = p.get("owner") or p.get("path")
            purpose = p.get("purpose") or "UNKNOWN"
            deps = p.get("dependencies") or []
            reps = p.get("representative_files") or []
            cmd_text = _package_command_text(p.get("commands") or {})
            detail: List[str] = [f"owner: {owner}", f"purpose: {purpose}"]
            if cmd_text:
                detail.append(f"commands: {cmd_text}")
            if deps:
                detail.append(f"deps: {', '.join(deps[:6])}")
            if reps:
                detail.append(f"files: {', '.join(reps[:2])}")
            out.append(f"- {p.get('path')} ({name}): " + "; ".join(detail))

    out.append("\n## Conventions")
    out.append(", ".join(c["conventions"]) if c.get("conventions") else "No tooling conventions detected.")

    if c.get("important_dependencies"):
        out.append("\n## Key dependencies")
        out.append(", ".join(c["important_dependencies"]))

    root_commands = c.get("commands") or {}
    cmds = [] if c.get("packages") and _all_primary_commands_unknown(root_commands) else _commands_lines(root_commands)
    if cmds:
        out.append("\n## Commands")
        out += cmds

    if c.get("pitfalls"):
        out.append("\n## Common pitfalls")
        out += [f"- {p}" for p in c["pitfalls"]]

    if c.get("critical_files"):
        out.append("\n## Important files")
        out += [f"- {f}" for f in c["critical_files"]]

    if c.get("structure"):
        out.append("\n## Repository structure")
        out.append(" ".join(c["structure"]))

    out.append(f"\n_As of scan {memory.get('scanned_at', '')} · confidence: {c.get('derivation_confidence', 'low')}._")
    return "\n".join(out).strip()


def _generate_claude_md_legacy(memory: Dict[str, Any]) -> str:
    """CLAUDE.md managed-block body — same source, directive formatting."""
    c = _ctx(memory)
    name = memory.get("repo_name", "this repository")
    out: List[str] = [f"# CLAUDE.md — project memory for {name}", ""]
    lead = f"You are working in **{name}**."
    if c.get("project_summary"):
        lead += f" {c['project_summary']}"
    out.append(lead)
    if c.get("stack"):
        out.append(f"Stack: {', '.join(c['stack'])}.")

    out.append("\n## How the codebase is organized")
    out.append(c.get("architecture_summary", "Not analyzed yet."))
    if c.get("key_subsystems"):
        out.append("Key areas: " + ", ".join(
            f"{s['name']} ({s.get('purpose', 'UNKNOWN')})" for s in c["key_subsystems"]
        ) + ".")

    if c.get("critical_files"):
        out.append("\n## Where to look first")
        out += [f"- {f}" for f in c["critical_files"]]

    out.append("\n## Conventions to follow")
    out.append("- " + "\n- ".join(c["conventions"]) if c.get("conventions") else "No specific tooling conventions detected.")

    cmds = _commands_lines(c.get("commands") or {})
    if cmds:
        out.append("\n## Commands (run tests after changes)")
        out += cmds

    if c.get("pitfalls"):
        out.append("\n## Watch out for")
        out += [f"- {p}" for p in c["pitfalls"]]

    out.append(f"\n_Maintained by Atlas from repository memory · as of scan {memory.get('scanned_at', '')}._")
    return "\n".join(out).strip()


def generate_claude_md(memory: Dict[str, Any]) -> str:
    """CLAUDE.md managed-block body: operational pointer, not duplicated facts."""
    c = _ctx(memory)
    name = memory.get("repo_name", "this repository")
    out: List[str] = [f"# CLAUDE.md - operational notes for {name}", ""]
    out.append("See AGENTS.md for repository facts, package breakdown, commands, dependencies, and important files.")
    out.append("Do not duplicate the AGENTS.md facts here; Atlas regenerates both managed blocks from repository_memory.")
    out.append("When changing code, prefer the package-specific commands listed in AGENTS.md.")
    claude_specific = c.get("claude_instructions") or []
    if claude_specific:
        out.append("\n## Claude-specific instructions")
        out += [f"- {item}" for item in claude_specific]

    out.append(f"\n_Maintained by Atlas from repository_memory as of scan {memory.get('scanned_at', '')}._")
    return "\n".join(out).strip()


_GENERATORS = {"agents": (generate_agents_md, "AGENTS.md"), "claude": (generate_claude_md, "CLAUDE.md")}


# --------------------------------------------------------------------------
# Generator + writer
# --------------------------------------------------------------------------
class AtlasManagedAgentsGenerator:
    """Generates AGENTS.md / CLAUDE.md from repository memory and writes the managed
    block without disturbing human-authored content."""

    def __init__(self, memory: Dict[str, Any]):
        self.memory = memory or {}

    def body(self, kind: str) -> str:
        gen, _ = _GENERATORS[kind]
        return gen(self.memory)

    def expected_block(self, kind: str) -> str:
        return wrap_block(self.body(kind))

    def write(self, repo_path: str, kind: str = "agents") -> Dict[str, Any]:
        if kind not in _GENERATORS:
            raise ValueError(f"unknown kind: {kind}")
        _, filename = _GENERATORS[kind]
        path = os.path.join(repo_path, filename)
        body = self.body(kind)
        existing = ""
        if os.path.isfile(path):
            try:
                with open(path, encoding="utf-8") as fh:
                    existing = fh.read()
            except OSError:
                existing = ""
        updated = apply_managed_block(existing, body)
        action = "unchanged"
        if _norm(updated) != _norm(existing):
            tmp = path + ".tmp"
            with open(tmp, "w", encoding="utf-8") as fh:
                fh.write(updated)
            os.replace(tmp, path)
            action = "created" if not existing else "updated"
        return {
            "path": path,
            "kind": kind,
            "action": action,
            "signature": block_signature(self.expected_block(kind)),
            "tokens": estimate_tokens(body),
        }

    def write_all(self, repo_path: str) -> List[Dict[str, Any]]:
        return [self.write(repo_path, k) for k in _GENERATORS]


# --------------------------------------------------------------------------
# Drift detection (reuses memory freshness; no duplicate system)
# --------------------------------------------------------------------------
def detect_drift(memory: Dict[str, Any], repo_path: str) -> Dict[str, Any]:
    """Report whether generated files + memory are current. Atlas refuses to claim
    'current' when any drift exists."""
    gen = AtlasManagedAgentsGenerator(memory)
    files: List[Dict[str, Any]] = []
    reasons: List[str] = []

    for kind, (_, filename) in _GENERATORS.items():
        path = os.path.join(repo_path, filename)
        expected = gen.expected_block(kind)
        state = "missing"
        if os.path.isfile(path):
            try:
                with open(path, encoding="utf-8") as fh:
                    actual = extract_block(fh.read())
            except OSError:
                actual = None
            if actual is None:
                state = "no_managed_block"
            elif _norm(actual) == _norm(expected):
                state = "in_sync"
            else:
                state = "out_of_sync"
        if state != "in_sync":
            reasons.append(f"{filename}: {state}")
        files.append({"file": filename, "kind": kind, "state": state})

    # Reuse existing freshness (memory-vs-code) from trust_integrity at scan time.
    freshness = str(memory.get("freshness_status") or "unknown")
    memory_fresh = freshness == "fresh"
    if not memory_fresh:
        reasons.append(f"memory freshness: {freshness} (rescan to refresh)")

    files_in_sync = all(f["state"] == "in_sync" for f in files)
    is_current = bool(memory_fresh and files_in_sync)
    # Confidence drops with each drift reason.
    confidence = "high" if is_current else ("medium" if files_in_sync or memory_fresh else "low")

    return {
        "is_current": is_current,        # Atlas only claims 'current' when True
        "memory_fresh": memory_fresh,
        "files_in_sync": files_in_sync,
        "files": files,
        "reasons": reasons,
        "confidence": confidence,
    }
